# Stage 5C — Post-Test Deep and Ensemble Evaluation

## 0. Stage Objective and Post-Test Disclosure

This section checks stage objective and post-test disclosure from saved, validated artifacts. It does not train, tune, or generate predictions. Stage 4L remains the official pre-registered Test evaluation. Stage 5C is descriptive only.

In [1]:
from pathlib import Path
import hashlib, json, os
import pandas as pd
from IPython.display import display
ROOT = Path.cwd()
CACHE_ONLY = os.environ.get('STAGE5C_CACHE_ONLY', '0') == '1'
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_evaluation_summary.json'
data=json.loads(path.read_text(encoding='utf-8'))
print({'stage_status':data['stage_status'],'evaluation_label':data['evaluation_label'],'stage4l_remains_official':data['stage4l_remains_official'],'stage6_started':data['stage6_started']})

{'stage_status': 'PASS', 'evaluation_label': 'Post-Test Extension', 'stage4l_remains_official': True, 'stage6_started': False}

## 1. Imports and Configuration

This section checks imports and configuration from saved, validated artifacts. It does not train, tune, or generate predictions.

In [2]:
from pathlib import Path
import hashlib, json, os
import pandas as pd
from IPython.display import display
ROOT = Path.cwd()
CACHE_ONLY = os.environ.get('STAGE5C_CACHE_ONLY', '0') == '1'
print({'stage':'stage5c','cache_only':CACHE_ONLY,'model_fit_calls':0,'preprocessing_fit_calls':0,'prediction_generation_calls':0,'source_access_calls':0})

{'stage': 'stage5c', 'cache_only': False, 'model_fit_calls': 0, 'preprocessing_fit_calls': 0, 'prediction_generation_calls': 0, 'source_access_calls': 0}

## 2. State Reconstruction

This section checks state reconstruction from saved, validated artifacts. It does not train, tune, or generate predictions.

In [3]:
text=(ROOT/'TASK.md').read_text(encoding='utf-8')
print(text.split('# Previous Stage Snapshot')[0][-3000:])

31. Frozen RealMLP observed Post-Test MAE is 62.159745 without sensitive Features and 61.821114 with sensitive Features. Stage 4L remains official; Stage 6 has not started.

# Open Questions

- None.

# Blockers

- Human authorization is required to exceed the explicit maximum of three Notebook attempts for one clean artifact-loading rerun. This rerun will load Stage 5C artifacts only and will perform zero source/model access, prediction generation, fitting, Bootstrap recomputation, or Registry writes.

# Verification Results

- Stage 4L Verification: PASS
- Stage 4L pre-Test freeze hash: PASS
- Stage 5A Verification: PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION
- Historical literal zero-Test-loading: FAIL, preserved
- Stage 5B Verification and Reviewer: PASS
- Stage 5B ensemble status: rejected
- Deep evaluation eligible: true
- Ensemble evaluation eligible: false
- Frozen RealMLP bundle/model hashes: PASS for both modes
- Protected baseline: PASS, 621 files
- Pre-evaluation freeze: PASS; SHA-256 `ea710f9369d9c9c4a37215ba030a999d154375881e1ecea5d4c0be010082cbaa`
- Safe-loader sentinel: PASS
- Test membership: PASS, 99,948 rows; row hash `e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e`
- Canonical target: PASS; hash `889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a`
- Without-sensitive prediction: PASS; SHA-256 `972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5`; two physical attempts, one successful prediction call
- With-sensitive prediction: PASS; SHA-256 `b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99`; one physical attempt, one successful prediction call
- Stage 4L official primary metrics reproduce: PASS
- RealMLP without minus Stage 4L MAE: 0.648114; paired 95% interval [0.453880, 0.845481]
- RealMLP with minus without sensitive MAE: -0.338631; paired 95% interval [-0.499985, -0.185015]; accuracy-only
- Model/preprocessing fits: 0/0
- Train Feature rows and source target values materialized: 0/0
- Ensemble and new Boosting Test predictions: 0/0
- Figures: PASS, 10 PNG files and 10 plotting-data files
- Registry: PASS, 362 unique IDs; seven Stage 5C rows; prior prefix preserved; second action REUSED
- Notebook: attempt 1 failed before artifact work; attempt 2 complete PASS; attempt 3 cache-only PASS; attempt budget 3/3
- Protected recheck: PASS, 621/621 unchanged
- Stage 6 started: false
- Independent Reviewer: one Major reporting inconsistency remains in saved Notebook output after the accepted signed-bias interpretation repair
- Final Stage 5C Verification: pending; PASS is prohibited until the authorized Notebook rerun and Reviewer closure

# Next Step

Obtain human authorization for one fourth clean artifact-loading Notebook run, execute it without source/model/prediction/Bootstrap/Registry writes, close the Reviewer Major issue, rerun protected verification, and issue final Stage 5C Verification. Only after PASS: Begin Stage 6 — Final Error Analysis and Model Comparison.

## 3. Stage 4L Official Evaluation Status

This section checks stage 4l official evaluation status from saved, validated artifacts. It does not train, tune, or generate predictions.

In [4]:
path=ROOT/'artifacts/reports/stage5c_stage4l_primary_validation.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "candidate_id": "stage4l__blend__without_sensitive",
  "canonical_target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "checks": {
    "candidate_id_exact": true,
    "finite_prediction": true,
    "finite_y_true": true,
    "official_metric_reproduction": true,
    "prediction_hash_exact": true,
    "row_count_exact": true,
    "row_ids_unique": true,
    "test_membership_exact": true,
    "zero_train_overlap": true
  },
  "evaluation_label": "Post-Test Extension",
  "first_stage5c_test_artifact_access_at_utc": "2026-07-15T23:50:30.857409+00:00",
  "metrics": {
    "mae": 61.511631217701016,
    "mape_percent": 33.13209268417578,
    "mean_signed_error": -9.554174474222766,
    "median_absolute_error": 35.5897020672497,
    "mse": 15822.736757025375,
    "negative_prediction_rate": 2.0010405410813623e-05,
    "p90_absolute_error": 131.5079529827791,
    "r_squared": 0.7122061518962177,
    "rmse": 125.78846034921239,
    "rmsle": 0.3838608580722206,
    "top_decile_mae": 195.49809883978568,
    "top_five_percent_mae": 287.0639693489494,
    "wape_percent": 24.949969976858977
  },
  "official_prediction_value_hash": "006dc882a39306271fba082f5f9b7bf5847c3ea7e14488d2c554f0fd044bcbdb",
  "official_role": "official_pre_registered_primary",
  "prediction_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "prediction_sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
  "preevaluation_freeze_path": "artifacts/reports/stage5c_preevaluation_freeze.json",
  "preevaluation_freeze_sha256": "ea710f9369d9c9c4a37215ba030a999d154375881e1ecea5d4c0be010082cbaa",
  "row_count": 99948,
  "runtime_seconds": 0.41145610000239685,
  "saved_metric_differences": {
    "mae": 0.0,
    "mape_percent": 0.0,
    "mean_signed_error": 0.0,
    "median_absolute_error": 0.0,
    "mse": 0.0,
    "negative_prediction_rate": 0.0,
    "p90_absolute_error": 0.0,
    "r_squared": 0.0,
    "rmse": -1.4210854715202004e-14,
    "rmsle": 0.0,
    "top_decile_mae": 0.0,
    "top_five_percent_mae": 0.0,
    "wape_percent": -3.552713678800501e-15
  },
  "sorted_test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "stage_id": "stage5c",
  "status": "PASS",
  "validated_at_utc": "2026-07-15T23:50:31.206060+00:00"
}

## 4. Stage 5A Frozen Deep Bundles

This section checks stage 5a frozen deep bundles from saved, validated artifacts. It does not train, tune, or generate predictions.

In [5]:
path=ROOT/'artifacts/manifests/stage5/stage5a2_full_train_manifest.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "checks": {
    "all_effective_configs_match": true,
    "all_proof_checks_pass": true,
    "all_reload_checks_pass": true,
    "both_results_pass": true,
    "direct_no_refit_contract": true,
    "epoch_30_both": true,
    "global_steps_exact": true,
    "no_early_stopping_or_restoration": true,
    "no_test_or_stage4l_evidence_used": true,
    "same_train_row_ids": true,
    "same_train_rows": true,
    "sensitive_attempt1_preserved": true,
    "sensitive_retry_used_once": true,
    "two_final_models": true,
    "zero_test_rows": true,
    "zero_validation_rows": true
  },
  "core_winner_family": "realmlp",
  "feature_schema": "deep_core_v1",
  "fixed_epoch": 30,
  "historical_lineage": {
    "deployed_refit_blocker": "artifacts/reports/stage5a2_fulltrain_blocker.json",
    "recovery1_blocker": "artifacts/reports/stage5a2_fulltrain_recovery_1_blocker.json",
    "sensitive_attempt1_technical_failure": "artifacts\\reports\\stage5a2_with_sensitive_attempt1_technical_failure.json"
  },
  "models": [
    {
      "best_checkpoint_restoration": false,
      "bundle_path": "artifacts\\models\\deep\\core_final\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "bundle_sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006",
      "bundle_size_bytes": 1042628,
      "candidate_id": "stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2",
      "completed_epoch": 30,
      "early_stopping": false,
      "effective_configuration_match": true,
      "effective_configuration_path": "artifacts\\reports\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_effective_config.json",
      "effective_configuration_sha256": "2ac1cd728f251ee2f39ca88f06a30234ddc29c67fd327e1d8c5219e4016c2c75",
      "epoch_proof_path": "artifacts\\reports\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_epoch_proof.json",
      "epoch_proof_sha256": "c6cbb3a73c75cb7ea612f4578f9f4c119fdb0fdcc48cfbf0c050ecbe8cac95e1",
      "final_global_step": 46830,
      "fit_time_seconds": 1086.07826140002,
      "history_length": 30,
      "history_path": "artifacts\\results\\stage5\\deep_core\\full_train\\histories\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_history.csv",
      "history_sha256": "946739eebad427d70a5d55562315353cb5ae3b1cdc81ab7bdd60d0a887cec6e5",
      "model_path": "artifacts\\models\\deep\\core_final\\components\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_model.joblib",
      "model_sha256": "be05e4f293cd719033c17862324e2c6f18673322b71ca79eb8c07dfa93f7efa3",
      "model_size_bytes": 1071174,
      "n_cv": 1,
      "n_refit": 0,
      "parent_elapsed_seconds": 1110.4589291000157,
      "peak_process_tree_ram_mib": 1643.2421875,
      "proof_checks_all": true,
      "reference_prediction_path": "artifacts\\predictions\\stage5\\deep_core\\full_train_reference\\stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.csv",
      "reference_prediction_sha256": "1f2ffe5f376d8ccb00900d4887e303b0a041f7be516a2a3df3eccbe74942df68",
      "reload_checks_all": true,
      "reload_path": "artifacts\\reports\\stage5a2_reload_stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.json",
      "reload_sha256": "ca4772a33b9e25d9873b2941adce991d7df9c46a9a43376a175107f9048ff57a",
      "requested_epoch": 30,
      "retry_count": 0,
      "sensitive_mode": "without_sensitive",
      "status": "PASS",
      "test_rows": 0,
      "train_row_id_hash": "7b6951ec62e3f969a88b82c360273564ed24213c0e5202cbb91ebb4059dad581",
      "training_rows": 399788,
      "val_fraction": 0.0,
      "validation_rows": 0
    },
    {
      "best_checkpoint_restoration": false,
      "bundle_path": "artifacts\\models\\deep\\core_final\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "bundle_sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600",
      "bundle_size_bytes": 1090518,
      "candidate_id": "stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1",
      "completed_epoch": 30,
      "early_stopping": false,
      "effective_configuration_match": true,
      "effective_configuration_path": "artifacts\\reports\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_effective_config.json",
      "effective_configuration_sha256": "a28d5f0947d48ff1ce8298da5b8202b1e322f178ba9f83eb6ccc4432aa9af44d",
      "epoch_proof_path": "artifacts\\reports\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_epoch_proof.json",
      "epoch_proof_sha256": "8565e016e29fcd43464889bb6335a29e432cf401bb676cf143dd00acb692cf73",
      "final_global_step": 46830,
      "fit_time_seconds": 948.4195894000004,
      "history_length": 30,
      "history_path": "artifacts\\results\\stage5\\deep_core\\full_train\\histories\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_history.csv",
      "history_sha256": "4880d1b94622b795bdff00f22abee95b32d00931eb73f06bdd37620f5664200e",
      "model_path": "artifacts\\models\\deep\\core_final\\components\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_model.joblib",
      "model_sha256": "e02ec0ab4f448a63dfd7a5a4e2f0785ce7542a0c8a947c2632cce13f78a9ed46",
      "model_size_bytes": 1119232,
      "n_cv": 1,
      "n_refit": 0,
      "parent_elapsed_seconds": 975.2164601999975,
      "peak_process_tree_ram_mib": 1728.34375,
      "proof_checks_all": true,
      "reference_prediction_path": "artifacts\\predictions\\stage5\\deep_core\\full_train_reference\\stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.csv",
      "reference_prediction_sha256": "f37fe5312c572280936f480087105875ef2fa83bb6ced08a68106045d71e7950",
      "reload_checks_all": true,
      "reload_path": "artifacts\\reports\\stage5a2_reload_stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.json",
      "reload_sha256": "cc84986046f83e3d5dffe3f90c52bcd740561f0e7fdd90a46ac3d9d46af20740",
      "requested_epoch": 30,
      "retry_count": 1,
      "sensitive_mode": "with_sensitive",
      "status": "PASS",
      "test_rows": 0,
      "train_row_id_hash": "7b6951ec62e3f969a88b82c360273564ed24213c0e5202cbb91ebb4059dad581",
      "training_rows": 399788,
      "val_fraction": 0.0,
      "validation_rows": 0
    }
  ],
  "official_stage_name": "Stage 5A2 — Top-Two Deep Validation and Core Final Models",
  "recovery_id": "stage5a2_fulltrain_recovery_2",
  "reload_verification_path": "artifacts\\reports\\stage5a2_core_reload_verification.csv",
  "stage_id": "stage5a2",
  "status": "PASS",
  "target_mode": "raw"
}

## 5. Stage 5A Governance Exception

This section checks stage 5a governance exception from saved, validated artifacts. It does not train, tune, or generate predictions.

In [6]:
path=ROOT/'artifacts/reports/stage5a2_governance_adjudication.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

## 6. Stage 5B Decision and Candidate Eligibility

This section checks stage 5b decision and candidate eligibility from saved, validated artifacts. It does not train, tune, or generate predictions.

In [7]:
path=ROOT/'artifacts/manifests/stage5/stage5b_evaluation_handoff.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "boost_weight": 0.5,
  "boosting_anchor_candidate_ids": {
    "catboost": "stage4l__catboost__without_sensitive",
    "lightgbm": "stage4l__lightgbm__without_sensitive",
    "xgboost": "stage4l__xgboost__without_sensitive"
  },
  "bootstrap_result": {
    "best_component_candidate_id": "stage4l__blend__without_sensitive",
    "boost_candidate_id": "stage4l__blend__without_sensitive",
    "bootstrap_mean": -0.2769272464378641,
    "bootstrap_median": -0.2787620559220554,
    "ci95_lower": -0.47107788971675446,
    "ci95_upper": -0.06945292104237374,
    "confirmation_pass": true,
    "ensemble_candidate_id": "stage5b__frozen_stage4_boosting_blend__deep-weight-0.50",
    "point_mae_difference": -0.2778740988612469,
    "resample_count": 500,
    "seed": 42,
    "win_proportion": 0.994
  },
  "deep_evaluation_eligible": true,
  "deep_final_bundle_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600"
    },
    "without_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006"
    }
  },
  "deep_validation_prediction_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/predictions/stage5/deep_core/final_validation/stage5a2__realmlp__core__with_sensitive.csv",
      "sha256": "9c8598b046053fa31043912e2f4578e51228fd6414e701c75f052da8ef566786"
    },
    "without_sensitive": {
      "path": "artifacts/predictions/stage5/deep_core/final_validation/stage5a2__realmlp__frozen.csv",
      "sha256": "8b8436ccfbf8a1d623c341e7d4ec956e6a0549fdec7288599746f282ac58b2e7"
    }
  },
  "deep_weight": 0.5,
  "ensemble_evaluation_eligible": false,
  "ensemble_specification_path": "artifacts/results/stage5/deep_boosting_ensemble/stage5b_frozen_ensemble.json",
  "ensemble_specification_sha256": "dba45a5966b3fa2f3b59a230ef1a801b17a9f5c0e1bbd5217418b5122799d0d5",
  "ensemble_status": "rejected",
  "frozen_internal_boosting_weights": {
    "catboost": 0.6,
    "lightgbm": 0.2,
    "xgboost": 0.2
  },
  "next_step": "Begin Stage 5C — Post-Test Deep and Ensemble Evaluation.",
  "non_sensitive_validation_metrics": {
    "mae": 62.853023806750166,
    "mape_percent": 34.248638310717666,
    "mean_signed_error": -9.799261295797683,
    "median_absolute_error": 36.81664155352183,
    "mse": 16914.923640032375,
    "negative_prediction_rate": 0.0,
    "p90_absolute_error": 132.47583538355516,
    "r_squared": 0.694641114227869,
    "rmse": 130.05738594955835,
    "rmsle": 0.38919461642191006,
    "top_decile_mae": 200.34909964944524,
    "top_five_percent_mae": 291.91568746357495,
    "wape_percent": 25.46038085712499
  },
  "required_stage4l_test_prediction_candidate_ids_for_later_discovery": [
    "stage4l__catboost__without_sensitive",
    "stage4l__lightgbm__without_sensitive",
    "stage4l__xgboost__without_sensitive",
    "stage4l__catboost__with_sensitive",
    "stage4l__lightgbm__with_sensitive",
    "stage4l__xgboost__with_sensitive"
  ],
  "sensitive_validation_metrics": {
    "mae": 62.27493817794243,
    "mape_percent": 34.18357160501904,
    "mean_signed_error": -8.822725626435485,
    "median_absolute_error": 36.556987926851065,
    "mse": 16457.676004180194,
    "negative_prediction_rate": 0.0,
    "p90_absolute_error": 131.5046853167313,
    "r_squared": 0.702895637368329,
    "rmse": 128.28747407358284,
    "rmsle": 0.3864417274133904,
    "top_decile_mae": 196.77241850894637,
    "top_five_percent_mae": 285.7723501480526,
    "wape_percent": 25.226211052936588
  },
  "stage5b_generated_test_predictions": false,
  "stage5b_loaded_test_artifacts": false,
  "stage5b_status": "PASS",
  "stage5c_may_evaluate_ensemble_only_when_accepted": true,
  "stage5c_must_evaluate_frozen_deep_exactly_once": true,
  "stage5c_must_not_change_weights": true,
  "stage_id": "stage5b",
  "status": "PASS",
  "target_hash": "ddb115eee1697b87e3d709119447571a0493c62f525b8c05072e51fbabe19668",
  "test_metric_values_included": false,
  "validation_row_id_hash": "5a47f42c454ab185f70a3cd2b637c55c9e4fa0804c59b2ebe25ac781c44fc26b"
}

## 7. Protected File Baseline

This section checks protected file baseline from saved, validated artifacts. It does not train, tune, or generate predictions.

In [8]:
path=ROOT/'artifacts/manifests/stage5/stage5c_protected_hashes_before.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

## 8. Pre-Evaluation Freeze

This section checks pre-evaluation freeze from saved, validated artifacts. It does not train, tune, or generate predictions.

In [9]:
path=ROOT/'artifacts/reports/stage5c_preevaluation_freeze.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "best_checkpoint_restoration": false,
  "bootstrap_settings": {
    "paired_indices": true,
    "resamples": 500,
    "seed": 42
  },
  "canonical_target_source": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "deep_candidate_count": 2,
  "deep_evaluation_candidate_ids": [
    "stage5c__realmlp__without_sensitive__test_evaluation",
    "stage5c__realmlp__with_sensitive__test_evaluation"
  ],
  "deep_evaluation_eligible": true,
  "deep_modes": {
    "with_sensitive": {
      "bundle_candidate_id": "stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1",
      "bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "bundle_sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600",
      "effective_configuration_path": "artifacts/reports/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_effective_config.json",
      "effective_configuration_sha256": "a28d5f0947d48ff1ce8298da5b8202b1e322f178ba9f83eb6ccc4432aa9af44d",
      "epoch_proof_path": "artifacts/reports/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_epoch_proof.json",
      "epoch_proof_sha256": "8565e016e29fcd43464889bb6335a29e432cf401bb676cf143dd00acb692cf73",
      "evaluation_candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "feature_schema_sha256": "415c973266ff04d826d8ccf5725c6ed43f1a9364fdebc40a66084fa82f695f9e",
      "model_path": "artifacts/models/deep/core_final/components/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_model.joblib",
      "model_sha256": "e02ec0ab4f448a63dfd7a5a4e2f0785ce7542a0c8a947c2632cce13f78a9ed46",
      "official_result_role": "post_test_sensitive_accuracy_candidate",
      "prediction_manifest_path": "artifacts/manifests/stage5/stage5c_prediction_manifest_with_sensitive.json",
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "reference_prediction_path": "artifacts/predictions/stage5/deep_core/full_train_reference/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.csv",
      "reference_prediction_sha256": "f37fe5312c572280936f480087105875ef2fa83bb6ced08a68106045d71e7950",
      "reload_report_path": "artifacts/reports/stage5a2_reload_stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.json",
      "reload_report_sha256": "cc84986046f83e3d5dffe3f90c52bcd740561f0e7fdd90a46ac3d9d46af20740",
      "required_feature_columns": [
        "applicant_income_000s",
        "population",
        "hud_median_family_income",
        "number_of_owner_occupied_units",
        "number_of_1_to_4_family_units",
        "log1p_applicant_income",
        "log1p_population",
        "log1p_hud_median_family_income",
        "log1p_owner_occupied_units",
        "log1p_1_to_4_family_units",
        "applicant_income_to_area_income",
        "tract_income_ratio",
        "owner_occupied_unit_ratio",
        "family_units_per_1000_people",
        "owner_occupied_units_per_1000_people",
        "has_co_applicant",
        "minority_population",
        "respondent_id",
        "agency_name",
        "loan_type_name",
        "property_type_name",
        "loan_purpose_name",
        "owner_occupancy_name",
        "preapproval_name",
        "msamd_name",
        "state_name",
        "county_name",
        "lien_status_name",
        "loan_program_group",
        "applicant_income_area_group",
        "tract_income_level",
        "us_region",
        "applicant_ethnicity_name",
        "co_applicant_ethnicity_name",
        "applicant_race_name_1",
        "co_applicant_race_name_1",
        "applicant_sex_name",
        "co_applicant_sex_name",
        "majority_minority_tract"
      ],
      "source_path": "data/regression_with_sensitive_features.csv",
      "source_sha256": "6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede"
    },
    "without_sensitive": {
      "bundle_candidate_id": "stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2",
      "bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "bundle_sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006",
      "effective_configuration_path": "artifacts/reports/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_effective_config.json",
      "effective_configuration_sha256": "2ac1cd728f251ee2f39ca88f06a30234ddc29c67fd327e1d8c5219e4016c2c75",
      "epoch_proof_path": "artifacts/reports/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_epoch_proof.json",
      "epoch_proof_sha256": "c6cbb3a73c75cb7ea612f4578f9f4c119fdb0fdcc48cfbf0c050ecbe8cac95e1",
      "evaluation_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "feature_schema_sha256": "89cb6ec8688d4b74a79f0979b0ff5e7e6c3d2b9a8f7fcb1bed8568d806b9738c",
      "model_path": "artifacts/models/deep/core_final/components/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_model.joblib",
      "model_sha256": "be05e4f293cd719033c17862324e2c6f18673322b71ca79eb8c07dfa93f7efa3",
      "official_result_role": "post_test_deep_candidate",
      "prediction_manifest_path": "artifacts/manifests/stage5/stage5c_prediction_manifest_without_sensitive.json",
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "reference_prediction_path": "artifacts/predictions/stage5/deep_core/full_train_reference/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.csv",
      "reference_prediction_sha256": "1f2ffe5f376d8ccb00900d4887e303b0a041f7be516a2a3df3eccbe74942df68",
      "reload_report_path": "artifacts/reports/stage5a2_reload_stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.json",
      "reload_report_sha256": "ca4772a33b9e25d9873b2941adce991d7df9c46a9a43376a175107f9048ff57a",
      "required_feature_columns": [
        "applicant_income_000s",
        "population",
        "hud_median_family_income",
        "number_of_owner_occupied_units",
        "number_of_1_to_4_family_units",
        "log1p_applicant_income",
        "log1p_population",
        "log1p_hud_median_family_income",
        "log1p_owner_occupied_units",
        "log1p_1_to_4_family_units",
        "applicant_income_to_area_income",
        "tract_income_ratio",
        "owner_occupied_unit_ratio",
        "family_units_per_1000_people",
        "owner_occupied_units_per_1000_people",
        "has_co_applicant",
        "respondent_id",
        "agency_name",
        "loan_type_name",
        "property_type_name",
        "loan_purpose_name",
        "owner_occupancy_name",
        "preapproval_name",
        "msamd_name",
        "state_name",
        "county_name",
        "lien_status_name",
        "loan_program_group",
        "applicant_income_area_group",
        "tract_income_level",
        "us_region"
      ],
      "source_path": "data/regression_without_sensitive_features.csv",
      "source_sha256": "e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c"
    }
  },
  "device": "CPU",
  "early_stopping": false,
  "elapsed_seconds": 1.3872037999972235,
  "ensemble_candidate_count": 0,
  "ensemble_evaluation_eligible": false,
  "ensemble_test_prediction_permitted": false,
  "evaluation_label": "Post-Test Extension",
  "expected_test_row_count": 99948,
  "figure_list": [
    "stage5c_test_mae_comparison",
    "stage5c_test_rmse_comparison",
    "stage5c_rmsle_r2_comparison",
    "stage5c_target_decile_mae",
    "stage5c_tail_error_comparison",
    "stage5c_absolute_error_difference_distribution",
    "stage5c_paired_bootstrap_interval",
    "stage5c_prediction_disagreement",
    "stage5c_sensitive_metric_difference",
    "stage5c_summary_dashboard"
  ],
  "freeze_timestamp_utc": "2026-07-15T23:49:48.051696+00:00",
  "frozen_epoch": 30,
  "frozen_family": "RealMLP",
  "frozen_target_mode": "raw",
  "historical_literal_zero_test_loading": "FAIL",
  "metric_contract_path": "artifacts/data_contract/metric_schema.json",
  "metric_contract_sha256": "4f73596e5608d59747f119367daa12ed11408f334a6c1c7f52484c8306e2f853",
  "metrics": [
    "mae",
    "mse",
    "rmse",
    "r_squared",
    "rmsle",
    "mape_percent",
    "median_absolute_error",
    "wape_percent",
    "mean_signed_error",
    "p90_absolute_error",
    "top_decile_mae",
    "top_five_percent_mae",
    "negative_prediction_rate"
  ],
  "model_or_preprocessing_fit_permitted": false,
  "next_stage": "Stage 6",
  "notebook_attempt_limit": 3,
  "official_comparator_candidate_id": "stage4l__blend__without_sensitive",
  "official_comparator_count": 1,
  "official_stage_name": "Stage 5C — Post-Test Deep and Ensemble Evaluation",
  "paired_comparisons": [
    "RealMLP without sensitive MAE - Stage 4L official primary MAE",
    "RealMLP with sensitive MAE - RealMLP without sensitive MAE"
  ],
  "post_test_statement": "Stage 5C is descriptive and does not replace the official Stage 4L pre-registered primary.",
  "precision": "float32",
  "prerequisite_checks": {
    "bundle_with_hash": true,
    "bundle_without_hash": true,
    "deep_eligible": true,
    "ensemble_ineligible": true,
    "epoch_30": true,
    "model_with_hash": true,
    "model_without_hash": true,
    "source_hashes": true,
    "split_hashes": true,
    "stage4l_freeze_hash": true,
    "stage4l_prediction_hash": true,
    "stage4l_primary_exact": true,
    "stage4l_verification_pass": true,
    "stage5a_literal_failure_visible": true,
    "stage5a_pass_with_exception": true,
    "stage5a_reloads_pass": true,
    "stage5a_two_models": true,
    "stage5b_ensemble_rejected": true,
    "stage5b_handoff_hash": true,
    "stage5b_reviewer_pass": true,
    "stage5b_spec_hash": true,
    "stage5b_verification_pass": true,
    "target_raw": true
  },
  "protected_baseline_path": "artifacts/manifests/stage5/stage5c_protected_hashes_before.json",
  "protected_baseline_sha256": "9fa746a0a47c11004a1eb2f2298388c5a2dd5e568ab4bac12ca35d05f3d4818d",
  "registry_ids": [
    "stage5c__realmlp__without_sensitive__test_evaluation",
    "stage5c__realmlp__with_sensitive__test_evaluation",
    "stage5c__realmlp_vs_stage4l__official_comparison",
    "stage5c__realmlp_vs_stage4l__paired_bootstrap",
    "stage5c__realmlp__sensitive_accuracy_comparison",
    "stage5c__evaluation_summary",
    "stage5c__stage6_handoff"
  ],
  "reviewer_cycle_limit": 2,
  "safe_loader_path": "stage5_safe_row_loader.py",
  "safe_loader_sentinel_required": true,
  "safe_loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "sensitive_policy": "Accuracy comparison only; not a fairness audit.",
  "sorted_test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "source_target_column": "loan_amount_000s",
  "source_target_columns_permitted": false,
  "stage4_prediction_metadata": {
    "prediction_sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
    "row_count": 99948
  },
  "stage4l_official_metric_row_reference": "artifacts/results/stage4/final_integration/stage4l_test_leaderboard.csv",
  "stage4l_official_prediction": {
    "metadata_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.metadata.json",
    "path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
    "sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
    "size_bytes": 30321039
  },
  "stage4l_official_primary_candidate_id": "stage4l__blend__without_sensitive",
  "stage4l_pretest_freeze": {
    "expected_sha256": "6c4aece5c82077be1932060f935fb4ce70213ded591ccdd41

## 9. Safe Test-Row Loader

This section checks safe test-row loader from saved, validated artifacts. It does not train, tune, or generate predictions.

In [10]:
path=ROOT/'artifacts/reports/stage5c_safe_loader_sentinel.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "checks": {
    "excluded_feature_values_not_converted": true,
    "excluded_target_values_not_converted": true,
    "only_allowed_ids_returned": true,
    "row_order_preserved": true,
    "source_unchanged": true,
    "target_not_requested": true
  },
  "converter_call_counts": {
    "feature_cat": 2,
    "feature_num": 2,
    "target": 0
  },
  "created_at_utc": "2026-07-15T23:49:54.848428+00:00",
  "evaluation_label": "Post-Test Extension",
  "excluded_rows_converted": 0,
  "loader_path": "stage5_safe_row_loader.py",
  "loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "source_target_values_materialized": 0,
  "stage_id": "stage5c",
  "status": "PASS"
}

## 10. Test Access Audit

This section checks test access audit from saved, validated artifacts. It does not train, tune, or generate predictions.

In [11]:
path=ROOT/'artifacts/reports/stage5c_test_access_audit.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "authorization_source": "Attached Stage 5C user specification",
  "bundle_load_timestamps": {
    "with_sensitive": "2026-07-15T23:52:27.512221+00:00",
    "without_sensitive": "2026-07-15T23:52:09.460163+00:00"
  },
  "canonical_target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "canonical_target_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "dataframe_materialization_scope": "99,948 Test Feature rows per sensitive mode",
  "ensemble_test_access": "none",
  "evaluation_label": "Post-Test Extension",
  "excluded_rows_converted": 0,
  "first_source_feature_access_at_utc": "2026-07-15T23:52:07.915625+00:00",
  "first_stage5c_test_artifact_access_at_utc": "2026-07-15T23:50:30.857409+00:00",
  "loader_path": "stage5_safe_row_loader.py",
  "loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "model_input_scope": "One frozen RealMLP input frame per sensitive mode",
  "new_boosting_prediction_generation": "none",
  "parser_conversion_scope": "Only exact saved Test Feature rows and required Feature columns",
  "physical_attempt_ids": [
    "with_sensitive_attempt1",
    "without_sensitive_attempt1",
    "without_sensitive_attempt2_technical_retry1"
  ],
  "prediction_generation_scope": "One successful full Test call per sensitive mode",
  "prediction_timestamps": {
    "with_sensitive": "2026-07-15T23:52:32.669499+00:00",
    "without_sensitive": "2026-07-15T23:52:15.011232+00:00"
  },
  "preevaluation_freeze_path": "artifacts/reports/stage5c_preevaluation_freeze.json",
  "preevaluation_freeze_sha256": "ea710f9369d9c9c4a37215ba030a999d154375881e1ecea5d4c0be010082cbaa",
  "raw_file_data_lines_scanned_per_source": 499736,
  "required_feature_columns": {
    "with_sensitive": [
      "applicant_income_000s",
      "population",
      "hud_median_family_income",
      "number_of_owner_occupied_units",
      "number_of_1_to_4_family_units",
      "log1p_applicant_income",
      "log1p_population",
      "log1p_hud_median_family_income",
      "log1p_owner_occupied_units",
      "log1p_1_to_4_family_units",
      "applicant_income_to_area_income",
      "tract_income_ratio",
      "owner_occupied_unit_ratio",
      "family_units_per_1000_people",
      "owner_occupied_units_per_1000_people",
      "has_co_applicant",
      "minority_population",
      "respondent_id",
      "agency_name",
      "loan_type_name",
      "property_type_name",
      "loan_purpose_name",
      "owner_occupancy_name",
      "preapproval_name",
      "msamd_name",
      "state_name",
      "county_name",
      "lien_status_name",
      "loan_program_group",
      "applicant_income_area_group",
      "tract_income_level",
      "us_region",
      "applicant_ethnicity_name",
      "co_applicant_ethnicity_name",
      "applicant_race_name_1",
      "co_applicant_race_name_1",
      "applicant_sex_name",
      "co_applicant_sex_name",
      "majority_minority_tract"
    ],
    "without_sensitive": [
      "applicant_income_000s",
      "population",
      "hud_median_family_income",
      "number_of_owner_occupied_units",
      "number_of_1_to_4_family_units",
      "log1p_applicant_income",
      "log1p_population",
      "log1p_hud_median_family_income",
      "log1p_owner_occupied_units",
      "log1p_1_to_4_family_units",
      "applicant_income_to_area_income",
      "tract_income_ratio",
      "owner_occupied_unit_ratio",
      "family_units_per_1000_people",
      "owner_occupied_units_per_1000_people",
      "has_co_applicant",
      "respondent_id",
      "agency_name",
      "loan_type_name",
      "property_type_name",
      "loan_purpose_name",
      "owner_occupancy_name",
      "preapproval_name",
      "msamd_name",
      "state_name",
      "county_name",
      "lien_status_name",
      "loan_program_group",
      "applicant_income_area_group",
      "tract_income_level",
      "us_region"
    ]
  },
  "saved_test_id_path": "artifacts/splits/test_row_ids.csv",
  "saved_test_id_sha256": "b01edf609d3102351b848d166e4db885da56db66a1fe441496e470dcf57770cb",
  "sentinel_path": "artifacts/reports/stage5c_safe_loader_sentinel.json",
  "sentinel_status": "PASS",
  "source_paths_and_hashes": {
    "with_sensitive": {
      "path": "data/regression_with_sensitive_features.csv",
      "sha256": "6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede"
    },
    "without_sensitive": {
      "path": "data/regression_without_sensitive_features.csv",
      "sha256": "e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c"
    }
  },
  "source_target_columns_requested": 0,
  "source_target_values_materialized": 0,
  "stage4l_official_prediction_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "stage4l_official_prediction_sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
  "stage_id": "stage5c",
  "status": "PASS",
  "test_feature_rows_materialized": {
    "with_sensitive": 99948,
    "without_sensitive": 99948
  },
  "test_feature_rows_materialized_across_all_physical_attempts": 299844,
  "train_feature_rows_materialized": {
    "with_sensitive": 0,
    "without_sensitive": 0
  }
}

## 11. Canonical Test Target and Official Comparator

This section checks canonical test target and official comparator from saved, validated artifacts. It does not train, tune, or generate predictions.

In [12]:
path=ROOT/'artifacts/reports/stage5c_stage4l_primary_validation.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "candidate_id": "stage4l__blend__without_sensitive",
  "canonical_target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "checks": {
    "candidate_id_exact": true,
    "finite_prediction": true,
    "finite_y_true": true,
    "official_metric_reproduction": true,
    "prediction_hash_exact": true,
    "row_count_exact": true,
    "row_ids_unique": true,
    "test_membership_exact": true,
    "zero_train_overlap": true
  },
  "evaluation_label": "Post-Test Extension",
  "first_stage5c_test_artifact_access_at_utc": "2026-07-15T23:50:30.857409+00:00",
  "metrics": {
    "mae": 61.511631217701016,
    "mape_percent": 33.13209268417578,
    "mean_signed_error": -9.554174474222766,
    "median_absolute_error": 35.5897020672497,
    "mse": 15822.736757025375,
    "negative_prediction_rate": 2.0010405410813623e-05,
    "p90_absolute_error": 131.5079529827791,
    "r_squared": 0.7122061518962177,
    "rmse": 125.78846034921239,
    "rmsle": 0.3838608580722206,
    "top_decile_mae": 195.49809883978568,
    "top_five_percent_mae": 287.0639693489494,
    "wape_percent": 24.949969976858977
  },
  "official_prediction_value_hash": "006dc882a39306271fba082f5f9b7bf5847c3ea7e14488d2c554f0fd044bcbdb",
  "official_role": "official_pre_registered_primary",
  "prediction_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "prediction_sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
  "preevaluation_freeze_path": "artifacts/reports/stage5c_preevaluation_freeze.json",
  "preevaluation_freeze_sha256": "ea710f9369d9c9c4a37215ba030a999d154375881e1ecea5d4c0be010082cbaa",
  "row_count": 99948,
  "runtime_seconds": 0.41145610000239685,
  "saved_metric_differences": {
    "mae": 0.0,
    "mape_percent": 0.0,
    "mean_signed_error": 0.0,
    "median_absolute_error": 0.0,
    "mse": 0.0,
    "negative_prediction_rate": 0.0,
    "p90_absolute_error": 0.0,
    "r_squared": 0.0,
    "rmse": -1.4210854715202004e-14,
    "rmsle": 0.0,
    "top_decile_mae": 0.0,
    "top_five_percent_mae": 0.0,
    "wape_percent": -3.552713678800501e-15
  },
  "sorted_test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "stage_id": "stage5c",
  "status": "PASS",
  "validated_at_utc": "2026-07-15T23:50:31.206060+00:00"
}

## 12. Test Feature Alignment

This section checks test feature alignment from saved, validated artifacts. It does not train, tune, or generate predictions.

In [13]:
path=ROOT/'artifacts/reports/stage5c_test_input_alignment_report.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "canonical_target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "canonical_targets_align_exactly": true,
  "common_feature_column_count": 31,
  "common_feature_values_equal": true,
  "evaluation_label": "Post-Test Extension",
  "excluded_rows_converted": 0,
  "loader_path": "stage5_safe_row_loader.py",
  "loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "prediction_rows_align_exactly": true,
  "schema_hashes": {
    "with_sensitive": "415c973266ff04d826d8ccf5725c6ed43f1a9364fdebc40a66084fa82f695f9e",
    "without_sensitive": "89cb6ec8688d4b74a79f0979b0ff5e7e6c3d2b9a8f7fcb1bed8568d806b9738c"
  },
  "sensitive_columns_only_in_expected_mode": true,
  "sentinel_status": "PASS",
  "source_frames_unchanged": true,
  "source_hashes": {
    "with_sensitive": "6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede",
    "without_sensitive": "e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c"
  },
  "source_target_values_materialized": 0,
  "stage_id": "stage5c",
  "status": "PASS",
  "test_feature_rows_materialized": {
    "with_sensitive": 99948,
    "without_sensitive": 99948
  },
  "test_row_count_per_mode": {
    "with_sensitive": 99948,
    "without_sensitive": 99948
  },
  "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "train_feature_rows_materialized": 0
}

## 13. Frozen Deep Prediction — Without Sensitive

This section checks frozen deep prediction — without sensitive from saved, validated artifacts. It does not train, tune, or generate predictions.

In [14]:
path=ROOT/'artifacts/manifests/stage5/stage5c_prediction_manifest_without_sensitive.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "attempt_id": "without_sensitive_attempt2_technical_retry1",
  "attempt_lineage": [
    "without_sensitive_attempt1",
    "without_sensitive_attempt2_technical_retry1"
  ],
  "bundle_candidate_id": "stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2",
  "bundle_checks": {
    "best_checkpoint_restoration_false": true,
    "device_cpu": true,
    "early_stopping_false": true,
    "family_realmlp": true,
    "features_exact": true,
    "fixed_epoch_30": true,
    "precision_float32": true,
    "row_id_not_feature": true,
    "sensitive_mode_match": true,
    "target_mode_raw": true,
    "target_not_feature": true,
    "test_rows_in_fit_zero": true,
    "training_rows_exact": true
  },
  "bundle_loaded_at_utc": "2026-07-15T23:52:09.460163+00:00",
  "bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
  "bundle_sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006",
  "candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
  "completed_at_utc": "2026-07-15T23:52:17.389874+00:00",
  "evaluation_label": "Post-Test Extension",
  "excluded_rows_converted": 0,
  "feature_column_hashes": {
    "agency_name": "e110348352f747af29fb716ff6bdfbfec6318344826022d136eb2df0afd0b6bd",
    "applicant_income_000s": "615af83897d971ab366bd058a42c628c38faaddebc37152ce5ca6305e8d65892",
    "applicant_income_area_group": "7f43122cd1ce6fce4ae6b7c20db1db2083f4a7b4b9ef39b0f9bf7ad73fff5706",
    "applicant_income_to_area_income": "05924b875abda806ede561be89d9534902d87b23a080ab81eb1a59df5e42ceb3",
    "county_name": "5d82f6fb5436abb099c2d00e44966e1d6136b1cbde85b03dc1fcb0a5b369c94e",
    "family_units_per_1000_people": "3a1ab007a9991603b5f7d08157871eb3d719ba79f07ddfc7d3231be53ad749c9",
    "has_co_applicant": "9234378e8c3476595e8abfb2ebc0440393efa7ef63d86ef41822b9870ecec1a7",
    "hud_median_family_income": "350d1ed698a22fc672cf521900598afa6a483692f46f2295289e4419fd8ea1c0",
    "lien_status_name": "9f419f6186810c4e3074f2fc07517f143f0369170ccdbd777fe7ef9bf7b41222",
    "loan_program_group": "54e4b4edddd6e8ca448a5b8eadae0cbd2d39905de4f1b0893a869a680e156127",
    "loan_purpose_name": "e44fe7da486e1de825d04974faabb8ada088e0831c898147f92531ec2b20ce2c",
    "loan_type_name": "1f78a758855135e6f573553f2052e7de6124ad841f195a33cb11b57a5cb9acbe",
    "log1p_1_to_4_family_units": "3f3da73756e499ae1827d05de8bb38b5cff2d1944a9d32ea764398fbb6190ae7",
    "log1p_applicant_income": "1878aeb21de9221e5419c8134373e4376af118ae430ab9356ee97a38b1bd0831",
    "log1p_hud_median_family_income": "f8b4ce1e70d757df07b505c1d0fa8ea1a254f387064e96491e51ec1c4d1b7cc4",
    "log1p_owner_occupied_units": "11edef4d4567ce2bcde01fcf1754b5b072b6a13a26a40c23d2037167b394aa3b",
    "log1p_population": "0ca9594aaf8e80d541cc52e5f717457c9aab41419bf632c8c9cb0edac80054af",
    "msamd_name": "399bf9c928e165d0177bbed410bdb13a79c06a4bae0d0b48247ca2790f8f9b6e",
    "number_of_1_to_4_family_units": "222fd1b62c3ce178aac9230aefaac65df989cd198c776608f43c602c73ecf9cc",
    "number_of_owner_occupied_units": "63000f41b4bb83d815e62a5f61f86c7e4fbd84a1bcb83a632ce782646ed6fafa",
    "owner_occupancy_name": "e4dd399ccd592a09249ef5cf8bb0cb6225ddb97f76049f16ad03bce6c1a4f2d7",
    "owner_occupied_unit_ratio": "5d5ede741052cf3c4211d091693909346cd865b942260fe783af62f572855642",
    "owner_occupied_units_per_1000_people": "c6bb85b497cca2b2b9816b9bdd4f3d7fd1b447ddcdf68cc60a29fc249d9c5f6e",
    "population": "6c54003651ace6814af8f6eb6b6f854783798f1c6d3c6dcc52359e0a5d8b8b37",
    "preapproval_name": "d5033486b3761f665c9335a07dd35f6c4c730e2c15784d4588df8d59675634b8",
    "property_type_name": "3920675cd880a804b36919f3895d428adc16598373f31d68a76bd4644cf2e42f",
    "respondent_id": "e9508cf0a82d386ae348898965fc8b42739236f90d07db24d8400ba38aed1ad3",
    "state_name": "2ca750ff8330cbbe826a42021df217056d545acaa7504fba01f3beea53737c5a",
    "tract_income_level": "2d09ca963c8aaced44d7983cf758777751a5401bbaa98d134b17c7380814b701",
    "tract_income_ratio": "5b35c3d0485bd9189da77bbc35c85553270ed47aac0e2aea84f18a71a5fb9fa7",
    "us_region": "2cb2a239e3842b5413f751ffea7307dc4efbe6b023952215097689a19acf8ffb"
  },
  "first_source_feature_access_at_utc": "2026-07-15T23:52:07.915625+00:00",
  "input_schema_hash": "89cb6ec8688d4b74a79f0979b0ff5e7e6c3d2b9a8f7fcb1bed8568d806b9738c",
  "model_fit_calls": 0,
  "model_path": "artifacts/models/deep/core_final/components/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2_model.joblib",
  "model_sha256": "be05e4f293cd719033c17862324e2c6f18673322b71ca79eb8c07dfa93f7efa3",
  "peak_process_tree_ram_mib": 555.8046875,
  "physical_attempt_count": 2,
  "prediction_call_count": 1,
  "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
  "prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5",
  "prediction_started_at_utc": "2026-07-15T23:52:15.011232+00:00",
  "prediction_value_hash": "9a51527bd3c861145bd3d5761f1881a53352b57454f319dbdfe22d6e350e5e43",
  "predictions_finite": true,
  "predictions_original_scale": true,
  "preprocessing_fit_calls": 0,
  "row_count": 99948,
  "runtime_seconds": 10.046677200007252,
  "safe_loader_path": "stage5_safe_row_loader.py",
  "safe_loader_sentinel_status": "PASS",
  "safe_loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "sensitive_mode": "without_sensitive",
  "source_frame_hash": "7beaeced263307df7f9a3eb7337d6d4d40684f49840860a243a655e644dcc09e",
  "source_frame_unchanged": true,
  "source_path": "data/regression_without_sensitive_features.csv",
  "source_scan_data_lines": 499736,
  "source_sha256": "e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c",
  "source_target_columns_requested": 0,
  "source_target_values_materialized": 0,
  "stage_id": "stage5c",
  "status": "PASS",
  "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "test_feature_rows_materialized": 99948,
  "test_id_file_sha256": "b01edf609d3102351b848d166e4db885da56db66a1fe441496e470dcf57770cb",
  "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "train_feature_rows_materialized": 0
}

## 14. Frozen Deep Prediction — With Sensitive

This section checks frozen deep prediction — with sensitive from saved, validated artifacts. It does not train, tune, or generate predictions.

In [15]:
path=ROOT/'artifacts/manifests/stage5/stage5c_prediction_manifest_with_sensitive.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "attempt_id": "with_sensitive_attempt1",
  "attempt_lineage": [
    "with_sensitive_attempt1"
  ],
  "bundle_candidate_id": "stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1",
  "bundle_checks": {
    "best_checkpoint_restoration_false": true,
    "device_cpu": true,
    "early_stopping_false": true,
    "family_realmlp": true,
    "features_exact": true,
    "fixed_epoch_30": true,
    "precision_float32": true,
    "row_id_not_feature": true,
    "sensitive_mode_match": true,
    "target_mode_raw": true,
    "target_not_feature": true,
    "test_rows_in_fit_zero": true,
    "training_rows_exact": true
  },
  "bundle_loaded_at_utc": "2026-07-15T23:52:27.512221+00:00",
  "bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
  "bundle_sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600",
  "candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
  "completed_at_utc": "2026-07-15T23:52:35.063052+00:00",
  "evaluation_label": "Post-Test Extension",
  "excluded_rows_converted": 0,
  "feature_column_hashes": {
    "agency_name": "e110348352f747af29fb716ff6bdfbfec6318344826022d136eb2df0afd0b6bd",
    "applicant_ethnicity_name": "6d041506010179568ecb3ba10e26a56af8ac22dc5b110de144980e5f97c0f6e7",
    "applicant_income_000s": "615af83897d971ab366bd058a42c628c38faaddebc37152ce5ca6305e8d65892",
    "applicant_income_area_group": "7f43122cd1ce6fce4ae6b7c20db1db2083f4a7b4b9ef39b0f9bf7ad73fff5706",
    "applicant_income_to_area_income": "05924b875abda806ede561be89d9534902d87b23a080ab81eb1a59df5e42ceb3",
    "applicant_race_name_1": "4d1f458451c17886a9f808c6277258ee46a9f3c019792bd34f44b44d0b74c2b0",
    "applicant_sex_name": "6a94897cc187bc6356426eaf9301e257d31f62402ab62609205a3a40f1de4785",
    "co_applicant_ethnicity_name": "430d5a970debe105ddd33cad1ed286bef9923d15aa977ef94705c9d3b48db868",
    "co_applicant_race_name_1": "64e22676c631541fffd83622db35bfdcc9b41e97ead642bb6959d9466673d666",
    "co_applicant_sex_name": "9dd527d53f535a63d746c065d30857fc113d6d513bd0f7a8ebf0a4b957a9646a",
    "county_name": "5d82f6fb5436abb099c2d00e44966e1d6136b1cbde85b03dc1fcb0a5b369c94e",
    "family_units_per_1000_people": "3a1ab007a9991603b5f7d08157871eb3d719ba79f07ddfc7d3231be53ad749c9",
    "has_co_applicant": "9234378e8c3476595e8abfb2ebc0440393efa7ef63d86ef41822b9870ecec1a7",
    "hud_median_family_income": "350d1ed698a22fc672cf521900598afa6a483692f46f2295289e4419fd8ea1c0",
    "lien_status_name": "9f419f6186810c4e3074f2fc07517f143f0369170ccdbd777fe7ef9bf7b41222",
    "loan_program_group": "54e4b4edddd6e8ca448a5b8eadae0cbd2d39905de4f1b0893a869a680e156127",
    "loan_purpose_name": "e44fe7da486e1de825d04974faabb8ada088e0831c898147f92531ec2b20ce2c",
    "loan_type_name": "1f78a758855135e6f573553f2052e7de6124ad841f195a33cb11b57a5cb9acbe",
    "log1p_1_to_4_family_units": "3f3da73756e499ae1827d05de8bb38b5cff2d1944a9d32ea764398fbb6190ae7",
    "log1p_applicant_income": "1878aeb21de9221e5419c8134373e4376af118ae430ab9356ee97a38b1bd0831",
    "log1p_hud_median_family_income": "f8b4ce1e70d757df07b505c1d0fa8ea1a254f387064e96491e51ec1c4d1b7cc4",
    "log1p_owner_occupied_units": "11edef4d4567ce2bcde01fcf1754b5b072b6a13a26a40c23d2037167b394aa3b",
    "log1p_population": "0ca9594aaf8e80d541cc52e5f717457c9aab41419bf632c8c9cb0edac80054af",
    "majority_minority_tract": "6399c7e849f6fe4ff567dd3b5bc02d55b03208b90f288f62e7a19e2ccbc307ab",
    "minority_population": "4ed4a55153ccdfa91b0a03823bea1bdcbee2f0966586a327e6c69b891cf44119",
    "msamd_name": "399bf9c928e165d0177bbed410bdb13a79c06a4bae0d0b48247ca2790f8f9b6e",
    "number_of_1_to_4_family_units": "222fd1b62c3ce178aac9230aefaac65df989cd198c776608f43c602c73ecf9cc",
    "number_of_owner_occupied_units": "63000f41b4bb83d815e62a5f61f86c7e4fbd84a1bcb83a632ce782646ed6fafa",
    "owner_occupancy_name": "e4dd399ccd592a09249ef5cf8bb0cb6225ddb97f76049f16ad03bce6c1a4f2d7",
    "owner_occupied_unit_ratio": "5d5ede741052cf3c4211d091693909346cd865b942260fe783af62f572855642",
    "owner_occupied_units_per_1000_people": "c6bb85b497cca2b2b9816b9bdd4f3d7fd1b447ddcdf68cc60a29fc249d9c5f6e",
    "population": "6c54003651ace6814af8f6eb6b6f854783798f1c6d3c6dcc52359e0a5d8b8b37",
    "preapproval_name": "d5033486b3761f665c9335a07dd35f6c4c730e2c15784d4588df8d59675634b8",
    "property_type_name": "3920675cd880a804b36919f3895d428adc16598373f31d68a76bd4644cf2e42f",
    "respondent_id": "e9508cf0a82d386ae348898965fc8b42739236f90d07db24d8400ba38aed1ad3",
    "state_name": "2ca750ff8330cbbe826a42021df217056d545acaa7504fba01f3beea53737c5a",
    "tract_income_level": "2d09ca963c8aaced44d7983cf758777751a5401bbaa98d134b17c7380814b701",
    "tract_income_ratio": "5b35c3d0485bd9189da77bbc35c85553270ed47aac0e2aea84f18a71a5fb9fa7",
    "us_region": "2cb2a239e3842b5413f751ffea7307dc4efbe6b023952215097689a19acf8ffb"
  },
  "first_source_feature_access_at_utc": "2026-07-15T23:52:25.611786+00:00",
  "input_schema_hash": "415c973266ff04d826d8ccf5725c6ed43f1a9364fdebc40a66084fa82f695f9e",
  "model_fit_calls": 0,
  "model_path": "artifacts/models/deep/core_final/components/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1_model.joblib",
  "model_sha256": "e02ec0ab4f448a63dfd7a5a4e2f0785ce7542a0c8a947c2632cce13f78a9ed46",
  "peak_process_tree_ram_mib": 584.703125,
  "physical_attempt_count": 1,
  "prediction_call_count": 1,
  "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
  "prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
  "prediction_started_at_utc": "2026-07-15T23:52:32.669499+00:00",
  "prediction_value_hash": "c979aad1634d7b8bd729a3a5e8568860f9042753bd6d66c0d45510e7f717d5fa",
  "predictions_finite": true,
  "predictions_original_scale": true,
  "preprocessing_fit_calls": 0,
  "row_count": 99948,
  "runtime_seconds": 10.054521899990505,
  "safe_loader_path": "stage5_safe_row_loader.py",
  "safe_loader_sentinel_status": "PASS",
  "safe_loader_sha256": "f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0",
  "sensitive_mode": "with_sensitive",
  "source_frame_hash": "a47fc53b40693253be727e1ce70b979f218cc89bfa423852249a59fefe08181a",
  "source_frame_unchanged": true,
  "source_path": "data/regression_with_sensitive_features.csv",
  "source_scan_data_lines": 499736,
  "source_sha256": "6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede",
  "source_target_columns_requested": 0,
  "source_target_values_materialized": 0,
  "stage_id": "stage5c",
  "status": "PASS",
  "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "test_feature_rows_materialized": 99948,
  "test_id_file_sha256": "b01edf609d3102351b848d166e4db885da56db66a1fe441496e470dcf57770cb",
  "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "train_feature_rows_materialized": 0
}

## 15. Prediction Artifact Validation

This section checks prediction artifact validation from saved, validated artifacts. It does not train, tune, or generate predictions.

In [16]:
path=ROOT/'artifacts/reports/stage5c_prediction_attempts.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "attempts": [
    {
      "attempt_id": "with_sensitive_attempt1",
      "completed_at_utc": "2026-07-15T23:52:35.064052+00:00",
      "evaluation_label": "Post-Test Extension",
      "excluded_rows_converted": 0,
      "first_source_feature_access_at_utc": "2026-07-15T23:52:25.611786+00:00",
      "manifest_path": "artifacts/manifests/stage5/stage5c_prediction_manifest_with_sensitive.json",
      "mode": "with_sensitive",
      "model_fit_calls": 0,
      "parent_timeout_seconds": 1200,
      "peak_process_tree_ram_mib": 584.703125,
      "prediction_calls": 1,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
      "preprocessing_fit_calls": 0,
      "runtime_seconds": 10.054521899990505,
      "source_target_values_materialized": 0,
      "started_at_utc": "2026-07-15T23:52:25.008579+00:00",
      "status": "PASS",
      "test_feature_rows_materialized": 99948,
      "train_feature_rows_materialized": 0
    },
    {
      "attempt_id": "without_sensitive_attempt1",
      "completed_at_utc": "2026-07-15T23:50:49.128370+00:00",
      "error": "'training_rows'",
      "error_type": "KeyError",
      "evaluation_label": "Post-Test Extension",
      "excluded_rows_converted": 0,
      "mode": "without_sensitive",
      "model_fit_calls": 0,
      "parent_timeout_seconds": 1200,
      "peak_process_tree_ram_mib": 440.3515625,
      "prediction_calls": 0,
      "preprocessing_fit_calls": 0,
      "runtime_seconds": 10.109807200002251,
      "source_target_values_materialized": 0,
      "started_at_utc": "2026-07-15T23:50:39.018008+00:00",
      "status": "FAIL",
      "test_feature_rows_materialized": 99948,
      "train_feature_rows_materialized": 0
    },
    {
      "attempt_id": "without_sensitive_attempt2_technical_retry1",
      "completed_at_utc": "2026-07-15T23:52:17.390869+00:00",
      "evaluation_label": "Post-Test Extension",
      "excluded_rows_converted": 0,
      "first_source_feature_access_at_utc": "2026-07-15T23:52:07.915625+00:00",
      "manifest_path": "artifacts/manifests/stage5/stage5c_prediction_manifest_without_sensitive.json",
      "mode": "without_sensitive",
      "model_fit_calls": 0,
      "parent_timeout_seconds": 1200,
      "peak_process_tree_ram_mib": 555.8046875,
      "prediction_calls": 1,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5",
      "preprocessing_fit_calls": 0,
      "runtime_seconds": 10.046677200007252,
      "source_target_values_materialized": 0,
      "started_at_utc": "2026-07-15T23:52:07.343230+00:00",
      "status": "PASS",
      "test_feature_rows_materialized": 99948,
      "train_feature_rows_materialized": 0
    }
  ],
  "evaluation_label": "Post-Test Extension",
  "maximum_physical_attempts": 4,
  "physical_attempt_count": 3,
  "stage_id": "stage5c",
  "status": "PASS",
  "successful_prediction_artifact_count": 2
}

## 16. Common Test Metrics

This section checks common test metrics from saved, validated artifacts. It does not train, tune, or generate predictions.

In [17]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_test_metrics.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,candidate_id,model_family,sensitive_mode,evaluation_stage,evaluation_label,official_result_role,prediction_path,prediction_sha256,row_count,test_row_id_hash,...,rmsle,mape_percent,median_absolute_error,wape_percent,mean_signed_error,p90_absolute_error,top_decile_mae,top_five_percent_mae,negative_prediction_rate,descriptive_mae_rank
0,stage4l__blend__without_sensitive,Frozen Stage 4 Boosting Blend,without_sensitive,Stage 4L,Official pre-registered evaluation,official_pre_registered_primary,artifacts/predictions/final_test/stage4l__blen...,9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfb...,99948,e58e4d078c761f60405e644d4dd7ba368f364daffb73b4...,...,0.383861,33.132093,35.589702,24.949970,-9.554174,131.507953,195.498099,287.063969,0.00002,1
1,stage5c__realmlp__without_sensitive__test_eval...,RealMLP,without_sensitive,Stage 5C,Post-Test Extension,post_test_extension,artifacts/predictions/stage5/posttest_evaluati...,972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc...,99948,e58e4d078c761f60405e644d4dd7ba368f364daffb73b4...,...,0.389685,33.592208,36.401075,25.212854,-7.013757,132.683744,191.740517,278.545533,0.00000,3
2,stage5c__realmlp__with_sensitive__test_evaluation,RealMLP,with_sensitive,Stage 5C,Post-Test Extension,post_test_extension_accuracy_only,artifacts/predictions/stage5/posttest_evaluati...,b4b11779a2d85209b2082c003ce79db2b657acd52c816c...,99948,e58e4d078c761f60405e644d4dd7ba368f364daffb73b4...,...,0.389633,33.696017,36.132471,25.075500,-6.440910,131.474865,190.956326,277.236066,0.00000,2

{'rows': 3, 'columns': ['candidate_id', 'model_family', 'sensitive_mode', 'evaluation_stage', 'evaluation_label', 'official_result_role', 'prediction_path', 'prediction_sha256', 'row_count', 'test_row_id_hash', 'target_hash', 'mae', 'mse', 'rmse', 'r_squared', 'rmsle', 'mape_percent', 'median_absolute_error', 'wape_percent', 'mean_signed_error', 'p90_absolute_error', 'top_decile_mae', 'top_five_percent_mae', 'negative_prediction_rate', 'descriptive_mae_rank']}

## 17. Official Stage 4L Comparison

This section checks official stage 4l comparison from saved, validated artifacts. It does not train, tune, or generate predictions.

In [18]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_official_comparison.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,metric,stage4l_value,deep_value,deep_minus_stage4l,relative_difference_percent,metric_direction,descriptive_interpretation,official_selection_effect,evaluation_label
0,mae,61.511631,62.159745,0.648114,1.053644,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
1,mse,15822.736757,15788.279771,-34.456986,-0.217769,lower_is_better,Observed value favors frozen RealMLP,none,Post-Test Extension
2,rmse,125.788460,125.651422,-0.137039,-0.108944,lower_is_better,Observed value favors frozen RealMLP,none,Post-Test Extension
3,r_squared,0.712206,0.712833,0.000627,0.087998,higher_is_better,Observed value favors frozen RealMLP,none,Post-Test Extension
4,rmsle,0.383861,0.389685,0.005824,1.517307,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
5,mape_percent,33.132093,33.592208,0.460116,1.388731,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
6,median_absolute_error,35.589702,36.401075,0.811373,2.279797,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
7,wape_percent,24.949970,25.212854,0.262884,1.053644,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
8,mean_signed_error,-9.554174,-7.013757,2.540418,-26.589610,closer_to_zero,Observed value favors frozen RealMLP,none,Post-Test Extension
9,p90_absolute_error,131.507953,132.683744,1.175791,0.894083,lower_is_better,Observed value favors Stage 4L primary,none,Post-Test Extension
10,top_decile_mae,195.498099,191.740517,-3.757582,-1.922056,lower_is_better,Observed value favors frozen RealMLP,none,Post-Test Extension
11,top_five_percent_mae,287.063969,278.545533,-8.518437,-2.967435,lower_is_better,Observed value favors frozen RealMLP,none,Post-Test Extension

{'rows': 13, 'columns': ['metric', 'stage4l_value', 'deep_value', 'deep_minus_stage4l', 'relative_difference_percent', 'metric_direction', 'descriptive_interpretation', 'official_selection_effect', 'evaluation_label']}

## 18. Paired Bootstrap

This section checks paired bootstrap from saved, validated artifacts. It does not train, tune, or generate predictions.

In [19]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_paired_bootstrap.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,comparison_id,first_candidate_id,second_candidate_id,point_mae_difference,bootstrap_mean,bootstrap_median,ci_2_5,ci_97_5,first_candidate_win_proportion,resamples,seed,evaluation_label,interpretation,row_hash,target_hash
0,realmlp_without_minus_stage4l_primary,stage5c__realmlp__without_sensitive__test_eval...,stage4l__blend__without_sensitive,0.648114,0.647066,0.643701,0.453880,0.845481,0.0,500,42,Post-Test Extension,Negative values favor the first-named Candidat...,e58e4d078c761f60405e644d4dd7ba368f364daffb73b4...,889e4253fb584c2a52a06d8b8e956beefad997ba18e4d7...
1,realmlp_with_minus_without_sensitive,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,-0.338631,-0.336300,-0.332808,-0.499985,-0.185015,1.0,500,42,Post-Test Extension,Negative values favor the first-named Candidat...,e58e4d078c761f60405e644d4dd7ba368f364daffb73b4...,889e4253fb584c2a52a06d8b8e956beefad997ba18e4d7...

{'rows': 2, 'columns': ['comparison_id', 'first_candidate_id', 'second_candidate_id', 'point_mae_difference', 'bootstrap_mean', 'bootstrap_median', 'ci_2_5', 'ci_97_5', 'first_candidate_win_proportion', 'resamples', 'seed', 'evaluation_label', 'interpretation', 'row_hash', 'target_hash']}

## 19. Sensitive Accuracy Comparison

This section checks sensitive accuracy comparison from saved, validated artifacts. It does not train, tune, or generate predictions. This is accuracy evidence, not a fairness audit or causal result.

In [20]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_sensitive_accuracy_comparison.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,metric,without_sensitive_value,with_sensitive_value,with_minus_without,relative_difference_percent,metric_direction,evaluation_label,descriptive_interpretation,scope_warning,paired_mae_ci_2_5,paired_mae_ci_97_5,paired_mae_point_difference
0,mae,62.159745,61.821114,-0.338631,-0.544776,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
1,mse,15788.279771,15630.041315,-158.238456,-1.002253,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
2,rmse,125.651422,125.020164,-0.631258,-0.502388,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
3,r_squared,0.712833,0.715711,0.002878,0.403761,higher_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
4,rmsle,0.389685,0.389633,-0.000052,-0.013432,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
5,mape_percent,33.592208,33.696017,0.103808,0.309025,lower_is_better,Post-Test Extension,Observed value favors without-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
6,median_absolute_error,36.401075,36.132471,-0.268604,-0.737902,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
7,wape_percent,25.212854,25.075500,-0.137354,-0.544776,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
8,mean_signed_error,-7.013757,-6.440910,0.572847,-8.167474,closer_to_zero,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
9,p90_absolute_error,132.683744,131.474865,-1.208879,-0.911098,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
10,top_decile_mae,191.740517,190.956326,-0.784191,-0.408986,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631
11,top_five_percent_mae,278.545533,277.236066,-1.309466,-0.470108,lower_is_better,Post-Test Extension,Observed value favors with-sensitive RealMLP,Accuracy comparison only; not a fairness audit...,-0.499985,-0.185015,-0.338631

{'rows': 13, 'columns': ['metric', 'without_sensitive_value', 'with_sensitive_value', 'with_minus_without', 'relative_difference_percent', 'metric_direction', 'evaluation_label', 'descriptive_interpretation', 'scope_warning', 'paired_mae_ci_2_5', 'paired_mae_ci_97_5', 'paired_mae_point_difference']}

## 20. Target-Decile and Tail Summary

This section checks target-decile and tail summary from saved, validated artifacts. It does not train, tune, or generate predictions.

In [21]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_target_decile_metrics.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,candidate_id,target_decile,row_count,target_min,target_max,target_mean,mae,rmse,median_absolute_error,mean_signed_error,underprediction_rate,overprediction_rate,evaluation_label
0,stage4l__blend__without_sensitive,1,10221,1.0,65.0,31.981117,26.882273,46.990603,12.263302,22.073110,0.276490,0.723510,Post-Test Extension
1,stage4l__blend__without_sensitive,2,9892,66.0,106.0,87.735847,41.904705,61.628817,29.044813,33.634989,0.231601,0.768399,Post-Test Extension
2,stage4l__blend__without_sensitive,3,9951,107.0,137.0,122.491609,36.781228,54.764106,24.720807,23.703652,0.329012,0.670988,Post-Test Extension
3,stage4l__blend__without_sensitive,4,10095,138.0,166.0,152.045468,37.374846,56.332616,25.608918,17.334614,0.414165,0.585835,Post-Test Extension
4,stage4l__blend__without_sensitive,5,9892,167.0,197.0,181.549939,38.009654,56.548760,27.838692,7.533381,0.501719,0.498281,Post-Test Extension
5,stage4l__blend__without_sensitive,6,9936,198.0,232.0,214.156099,44.971094,64.876093,33.321439,3.909475,0.550523,0.449477,Post-Test Extension
6,stage4l__blend__without_sensitive,7,10012,233.0,277.0,253.876348,49.709994,69.378948,39.336360,-8.602889,0.622253,0.377747,Post-Test Extension
7,stage4l__blend__without_sensitive,8,10084,278.0,344.0,307.769139,61.548825,82.447553,50.959508,-19.726540,0.671261,0.328739,Post-Test Extension
8,stage4l__blend__without_sensitive,9,9884,345.0,444.0,391.803824,82.839169,107.575813,69.478488,-36.211759,0.706192,0.293808,Post-Test Extension
9,stage4l__blend__without_sensitive,10,9981,445.0,10000.0,726.470795,195.913130,340.155223,124.642560,-139.716295,0.790803,0.209197,Post-Test Extension
10,stage5c__realmlp__without_sensitive__test_eval...,1,10221,1.0,65.0,31.981117,26.677868,47.105281,12.390781,21.622162,0.288817,0.711183,Post-Test Extension
11,stage5c__realmlp__without_sensitive__test_eval...,2,9892,66.0,106.0,87.735847,42.710375,63.699382,29.508539,33.833529,0.242924,0.757076,Post-Test Extension

{'rows': 30, 'columns': ['candidate_id', 'target_decile', 'row_count', 'target_min', 'target_max', 'target_mean', 'mae', 'rmse', 'median_absolute_error', 'mean_signed_error', 'underprediction_rate', 'overprediction_rate', 'evaluation_label']}

## 21. Prediction and Residual Disagreement

This section checks prediction and residual disagreement from saved, validated artifacts. It does not train, tune, or generate predictions.

In [22]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_disagreement_summary.csv'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

,comparison_id,pearson_prediction_correlation,spearman_prediction_correlation,pearson_residual_correlation,spearman_residual_correlation,mean_absolute_prediction_disagreement,median_absolute_prediction_disagreement,first_candidate_lower_absolute_error_percent,second_candidate_lower_absolute_error_percent,opposite_signed_error_percent,highest_decile_residual_correlation,evaluation_label
0,realmlp_without_vs_stage4l_primary,0.984343,0.988733,0.964374,0.943720,16.691883,9.292099,47.682795,52.317205,9.070717,0.963688,Post-Test Extension
1,realmlp_with_vs_without_sensitive,0.989189,0.992052,0.974628,0.958913,14.214083,8.302328,50.656341,49.338656,7.946132,0.973162,Post-Test Extension

{'rows': 2, 'columns': ['comparison_id', 'pearson_prediction_correlation', 'spearman_prediction_correlation', 'pearson_residual_correlation', 'spearman_residual_correlation', 'mean_absolute_prediction_disagreement', 'median_absolute_prediction_disagreement', 'first_candidate_lower_absolute_error_percent', 'second_candidate_lower_absolute_error_percent', 'opposite_signed_error_percent', 'highest_decile_residual_correlation', 'evaluation_label']}

## 22. Post-Test Interpretation

This section checks post-test interpretation from saved, validated artifacts. It does not train, tune, or generate predictions. Stage 4L remains the official pre-registered Test evaluation. Stage 5C is descriptive only.

In [23]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_evaluation_summary.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "bootstrap_summaries": [
    {
      "bootstrap_mean": 0.6470662879579675,
      "bootstrap_median": 0.6437009448438786,
      "ci_2_5": 0.4538804170824676,
      "ci_97_5": 0.8454810733773875,
      "comparison_id": "realmlp_without_minus_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "first_candidate_win_proportion": 0.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": 0.6481138711769034,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage4l__blend__without_sensitive",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    },
    {
      "bootstrap_mean": -0.336300459564,
      "bootstrap_median": -0.33280776930222444,
      "ci_2_5": -0.4999854010698824,
      "ci_97_5": -0.18501466804360983,
      "comparison_id": "realmlp_with_minus_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "first_candidate_win_proportion": 1.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": -0.3386313586895753,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    }
  ],
  "bundle_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600"
    },
    "without_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006"
    }
  },
  "deep_candidate_metrics": {
    "stage5c__realmlp__with_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "descriptive_mae_rank": 2,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 61.821113730188344,
      "mape_percent": 33.69601671665242,
      "mean_signed_error": -6.440909963862778,
      "median_absolute_error": 36.132470639483515,
      "model_family": "RealMLP",
      "mse": 15630.041315267528,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension_accuracy_only",
      "p90_absolute_error": 131.47486522058995,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
      "r_squared": 0.7157110173026984,
      "rmse": 125.02016363478144,
      "rmsle": 0.38963286174723183,
      "row_count": 99948,
      "sensitive_mode": "with_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 190.95632563103865,
      "top_five_percent_mae": 277.2360664352556,
      "wape_percent": 25.075500372364072
    },
    "stage5c__realmlp__without_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "descriptive_mae_rank": 3,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 62.15974508887792,
      "mape_percent": 33.592208457007786,
      "mean_signed_error": -7.013756750327312,
      "median_absolute_error": 36.401075066386284,
      "model_family": "RealMLP",
      "mse": 15788.279771452735,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension",
      "p90_absolute_error": 132.6837437649384,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5",
      "r_squared": 0.7128328771349854,
      "rmse": 125.65142168496438,
      "rmsle": 0.3896852047427889,
      "row_count": 99948,
      "sensitive_mode": "without_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 191.74051657000007,
      "top_five_percent_mae": 278.5455325828293,
      "wape_percent": 25.212853943798812
    }
  },
  "deep_prediction_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99"
    },
    "without_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5"
    }
  },
  "disagreement_summary": [
    {
      "comparison_id": "realmlp_without_vs_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 47.68279505342778,
      "highest_decile_residual_correlation": 0.9636875408818423,
      "mean_absolute_prediction_disagreement": 16.691883310505084,
      "median_absolute_prediction_disagreement": 9.292098685819383,
      "opposite_signed_error_percent": 9.070716772721815,
      "pearson_prediction_correlation": 0.9843433578350852,
      "pearson_residual_correlation": 0.9643741298382964,
      "second_candidate_lower_absolute_error_percent": 52.31720494657222,
      "spearman_prediction_correlation": 0.9887334489607951,
      "spearman_residual_correlation": 0.9437204953726724
    },
    {
      "comparison_id": "realmlp_with_vs_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 50.65634129747468,
      "highest_decile_residual_correlation": 0.9731624204509146,
      "mean_absolute_prediction_disagreement": 14.214082689582696,
      "median_absolute_prediction_disagreement": 8.302328345393661,
      "opposite_signed_error_percent": 7.9461319886340895,
      "pearson_prediction_correlation": 0.9891892219308128,
      "pearson_residual_correlation": 0.9746284352649397,
      "second_candidate_lower_absolute_error_percent": 49.33865610117261,
      "spearman_prediction_correlation": 0.9920515014896281,
      "spearman_residual_correlation": 0.958912522779644
    }
  ],
  "ensemble_status": "rejected",
  "ensemble_test_prediction_count": 0,
  "evaluation_label": "Post-Test Extension",
  "inherited_stage5a_governance_status": "PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION",
  "model_fit_calls": 0,
  "new_boosting_prediction_count": 0,
  "next_stage": "Stage 6",
  "official_comparison": [
    {
      "deep_minus_stage4l": 0.6481138711769034,
      "deep_value": 62.15974508887792,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mae",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518561,
      "stage4l_value": 61.511631217701016
    },
    {
      "deep_minus_stage4l": -34.456985572640406,
      "deep_value": 15788.279771452735,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.2177688101733812,
      "stage4l_value": 15822.736757025375
    },
    {
      "deep_minus_stage4l": -0.13703866424800992,
      "deep_value": 125.65142168496438,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.10894374878869242,
      "stage4l_value": 125.78846034921239
    },
    {
      "deep_minus_stage4l": 0.0006267252387677225,
      "deep_value": 0.7128328771349854,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "r_squared",
      "metric_direction": "higher_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.08799772890182062,
      "stage4l_value": 0.7122061518962177
    },
    {
      "deep_minus_stage4l": 0.005824346670568303,
      "deep_value": 0.3896852047427889,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmsle",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.5173067396917284,
      "stage4l_value": 0.3838608580722206
    },
    {
      "deep_minus_stage4l": 0.46011577283200467,
      "deep_value": 33.592208457007786,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.3887313947173658,
      "stage4l_value": 33.13209268417578
    },
    {
      "deep_minus_stage4l": 0.8113729991365801,
      "deep_value": 36.401075066386284,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "median_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 2.279797109858979,
      "stage4l_value": 35.5897020672497
    },
    {
      "deep_minus_stage4l": 0.2628839669398353,
      "deep_value": 25.212853943798812,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "wape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518475,
      "stage4l_value": 24.949969976858977
    },
    {
      "deep_minus_stage4l": 2.5404177238954535,
      "deep_value": -7.013756750327312,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mean_signed_error",
      "metric_direction": "closer_to_zero",
      "official_selection_effect": "none",
      "relative_difference_percent": -26.58960992129168,
      "stage4l_value": -9.554174474222766
    },
    {
      "deep_minus_stage4l": 1.1757907821593108,
      "deep_value": 132.6837437649384,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "p90_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.8940834036959574,
      "stage4l_value": 131.5079529827791
    },
    {
      "deep_minus_stage4l": -3.7575822697856154,
      "deep_value": 191.7405165

## 23. Test Evaluation Visualizations

This section checks test evaluation visualizations from saved, validated artifacts. It does not train, tune, or generate predictions.

In [24]:
path=ROOT/'artifacts/manifests/stage5/stage5c_visualization_manifest.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "evaluation_label": "Post-Test Extension",
  "figure_count": 10,
  "figures": [
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_test_mae_comparison.png",
      "figure_sha256": "17de57d6c5383b7ea0ccd85f8d411615858f6c2b696ebecdd7c863619591af7c",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_test_mae_comparison.csv",
      "plotting_data_sha256": "947f78da519015c2bfe7180930896d331cc355305b063f7190400c8da49c2007",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "MAE Comparison\nPost-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_test_rmse_comparison.png",
      "figure_sha256": "41d4a3ad1e224fd9b41af0c432b654bdd9447891c1fe7dababe3f88ca9bfd147",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_test_rmse_comparison.csv",
      "plotting_data_sha256": "32c61c321f7f4d57e5f331a15bca6713d07a28acb8207f7be8b21ab629b656a8",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "RMSE Comparison\nPost-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_rmsle_r2_comparison.png",
      "figure_sha256": "43f430b4c773df7db11e27c896524109032ab20bc06c1af45cd47b3a174e5110",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_rmsle_r2_comparison.csv",
      "plotting_data_sha256": "2f606e098a613376168589059d4fe1ce83d4c49d09e1dae26ee6ef2409189d4d",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "RMSLE and R² Comparison — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_target_decile_mae.png",
      "figure_sha256": "714ab0c8da6ee224182484776975ffadac98ff5b224ea77a6332efe7a3a2a3ab",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_target_decile_mae.csv",
      "plotting_data_sha256": "52fc5178a105aa12eab54dd78c15417bdfc4560440832a37859cf328d1c33f76",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Target-Decile MAE — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_tail_error_comparison.png",
      "figure_sha256": "da7998f2328c05a0cb6729c068117c86ed3ba903b9066f04f23c7704ddc8dd05",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_tail_error_comparison.csv",
      "plotting_data_sha256": "91b854970abf3dacf8df1241727d5fb5c7d2d8067127c7e99def75481b192db4",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Tail-Error Comparison — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_absolute_error_difference_distribution.png",
      "figure_sha256": "b6d6e178f56ad12d5d2be4915e650ceb2b29576ad52daf35dcc82c30bc9522d7",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_absolute_error_difference_distribution.csv",
      "plotting_data_sha256": "9057cb67dfaee0aa8b52d290046d9cebc1038038a4aa5be7be2e1ff510423dd7",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Paired Absolute-Error Difference — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_paired_bootstrap_interval.png",
      "figure_sha256": "4f0762e3608dabe435b6dd8ffdacc92e22cd97e730b347412334ea20f93f3fb2",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_paired_bootstrap_interval.csv",
      "plotting_data_sha256": "21c6a72b4abb3a7318d0a32cc64febddbc312676f37ae5b1c8aaaf15f3018e4f",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Paired Bootstrap MAE Intervals — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_prediction_disagreement.png",
      "figure_sha256": "0f5757243fbc89f25bb789bad456530601cb66112062a5fd4caeaea643be4f0b",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_prediction_disagreement.csv",
      "plotting_data_sha256": "b1cb6233e7a63b5d07072e0ca2b74974953ba0d1cec9e7c820b357da2f46b4df",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Prediction Disagreement View — Post-Test Extension"
    },
    {
      "candidate_ids": [
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_sensitive_metric_difference.png",
      "figure_sha256": "8da84f90baf0a64b7f66afcb7e9f2147297f86cd67412552adf5fffd973dcf22",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_sensitive_metric_difference.csv",
      "plotting_data_sha256": "d03eef9f500dfbde2bf0bd17aedd55bc250a8084fd6688f6b0ae831295ee7547",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Sensitive-Mode Accuracy Differences — Post-Test Extension\nNot a fairness audit"
    },
    {
      "candidate_ids": [
        "stage4l__blend__without_sensitive",
        "stage5c__realmlp__without_sensitive__test_evaluation",
        "stage5c__realmlp__with_sensitive__test_evaluation"
      ],
      "evaluation_label": "Post-Test Extension",
      "figure_path": "artifacts/figures/stage5c/stage5c_summary_dashboard.png",
      "figure_sha256": "88b26702b584881def572f329cae5b329af293b4f2c1fc45ce3a5bf4f05d94c1",
      "interpretation_scope": "Descriptive Test evaluation only; no model selection.",
      "plotting_data_path": "artifacts/figures/stage5c/plotting_data/stage5c_summary_dashboard.csv",
      "plotting_data_sha256": "de19996d7d46a4f85c4e6d59f738ef93c4706ddaa09d820cbc8aac53f6cf403b",
      "test_row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "title": "Stage 5C Summary Dashboard — Post-Test Extension"
    }
  ],
  "stage_id": "stage5c",
  "status": "PASS"
}

## 24. Registry Update

This section checks registry update from saved, validated artifacts. It does not train, tune, or generate predictions.

In [25]:
path=ROOT/'artifacts/reports/stage5c_registry_update.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "action": "REUSED",
  "evaluation_label": "Post-Test Extension",
  "prior_byte_count": 247798,
  "prior_prefix_preserved": true,
  "prior_sha256": "da5501ee01e2131c642ca34af570ea7775cdce8a1cfa5a373a54c6cef66b4b5c",
  "registry_row_count": 362,
  "registry_sha256": "27b0ef62e59dec653c6a68459db765790b8ad1947f62fa5caaca6e84cf975522",
  "registry_unique_ids": true,
  "second_action": "REUSED",
  "stage5c_registry_ids": [
    "stage5c__realmlp__without_sensitive__test_evaluation",
    "stage5c__realmlp__with_sensitive__test_evaluation",
    "stage5c__realmlp_vs_stage4l__official_comparison",
    "stage5c__realmlp_vs_stage4l__paired_bootstrap",
    "stage5c__realmlp__sensitive_accuracy_comparison",
    "stage5c__evaluation_summary",
    "stage5c__stage6_handoff"
  ],
  "stage5c_row_count": 7,
  "stage_id": "stage5c",
  "status": "PASS"
}

## 25. Stage 6 Handoff

This section checks stage 6 handoff from saved, validated artifacts. It does not train, tune, or generate predictions.

In [26]:
path=ROOT/'artifacts/manifests/stage5/stage5c_stage6_handoff.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "accepted_ensemble_count": 0,
  "artifact_paths_and_hashes": {
    "bootstrap": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_paired_bootstrap.csv",
      "sha256": "9e49560e3a7fbb997e42018143bb945974157b6af8a97cf095767fac8a1e6b17"
    },
    "common_metrics": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_test_metrics.csv",
      "sha256": "6c95dfaa3b5873880159b0f9f90df2e59bc202a90832df176e80a8a877b0d575"
    },
    "decile_metrics": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_target_decile_metrics.csv",
      "sha256": "da0ca727d2ea4131c8c51b9f54003c3d7f24051690ce08c0ab47ede37d6be99d"
    },
    "disagreement_by_decile": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_disagreement_by_target_decile.csv",
      "sha256": "7480d6fd8791d22e21d090fd29a60f27b5c94317d3989cb17bb037aac4896f00"
    },
    "disagreement_summary": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_disagreement_summary.csv",
      "sha256": "56eea8e0643d2e9cf0713d05f198c6f9de557488b46abcd08fffc1ac90cc9834"
    },
    "official_comparison": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_official_comparison.csv",
      "sha256": "cf7d44a4d1e45edaf9f46e471e3b7535f8b43b41a038ab2c29d14794d85097a7"
    },
    "sensitive_accuracy": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_sensitive_accuracy_comparison.csv",
      "sha256": "ea774bf4655a2ecd38c0594d0f0cee698ce9c6a55da9312c3b641ffbeb736563"
    },
    "tail_metrics": {
      "path": "artifacts/results/stage5/posttest_evaluation/stage5c_tail_metrics.csv",
      "sha256": "3a860057656de94febe1f158f9a6a7911e571276abad6871a9d0e357c8f8da6c"
    }
  },
  "ensemble_status": "rejected",
  "ensemble_test_prediction_path": null,
  "evaluation_label": "Post-Test Extension",
  "next_stage": "Stage 6",
  "post_test_extension": true,
  "recommended_bounded_stage6_analyses": [
    "error distributions",
    "target deciles",
    "tail behavior",
    "worst predictions",
    "underprediction and overprediction",
    "model disagreement",
    "sensitive and non-sensitive accuracy differences"
  ],
  "stage4l_official_prediction_path": "artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv",
  "stage4l_official_prediction_sha256": "9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed",
  "stage4l_official_primary_candidate_id": "stage4l__blend__without_sensitive",
  "stage4l_official_result_remains_unchanged": true,
  "stage5a_governance_exception_summary": "Historical literal zero-Test-loading failed under an accepted procedural exception; zero Test rows entered learned preprocessing, fitting, selection, or Validation metrics.",
  "stage5c_results_are_descriptive": true,
  "stage5c_status": "PASS",
  "stage6_must_not_rerun_model_inference": true,
  "stage6_must_use_saved_predictions": true,
  "stage6_started": false,
  "stage7_owns_full_fairness_analysis": true,
  "stage8_owns_final_explainability": true,
  "stage_id": "stage5c",
  "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
  "test_row_count": 99948,
  "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
  "with_sensitive_bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
  "with_sensitive_bundle_sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600",
  "with_sensitive_deep_candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
  "with_sensitive_prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
  "with_sensitive_prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
  "without_sensitive_bundle_path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
  "without_sensitive_bundle_sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006",
  "without_sensitive_deep_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
  "without_sensitive_prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
  "without_sensitive_prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5"
}

## 26. Stage 5C Artifact Summary

This section checks stage 5c artifact summary from saved, validated artifacts. It does not train, tune, or generate predictions.

In [27]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_evaluation_summary.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "bootstrap_summaries": [
    {
      "bootstrap_mean": 0.6470662879579675,
      "bootstrap_median": 0.6437009448438786,
      "ci_2_5": 0.4538804170824676,
      "ci_97_5": 0.8454810733773875,
      "comparison_id": "realmlp_without_minus_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "first_candidate_win_proportion": 0.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": 0.6481138711769034,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage4l__blend__without_sensitive",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    },
    {
      "bootstrap_mean": -0.336300459564,
      "bootstrap_median": -0.33280776930222444,
      "ci_2_5": -0.4999854010698824,
      "ci_97_5": -0.18501466804360983,
      "comparison_id": "realmlp_with_minus_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "first_candidate_win_proportion": 1.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": -0.3386313586895753,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    }
  ],
  "bundle_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600"
    },
    "without_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006"
    }
  },
  "deep_candidate_metrics": {
    "stage5c__realmlp__with_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "descriptive_mae_rank": 2,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 61.821113730188344,
      "mape_percent": 33.69601671665242,
      "mean_signed_error": -6.440909963862778,
      "median_absolute_error": 36.132470639483515,
      "model_family": "RealMLP",
      "mse": 15630.041315267528,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension_accuracy_only",
      "p90_absolute_error": 131.47486522058995,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
      "r_squared": 0.7157110173026984,
      "rmse": 125.02016363478144,
      "rmsle": 0.38963286174723183,
      "row_count": 99948,
      "sensitive_mode": "with_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 190.95632563103865,
      "top_five_percent_mae": 277.2360664352556,
      "wape_percent": 25.075500372364072
    },
    "stage5c__realmlp__without_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "descriptive_mae_rank": 3,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 62.15974508887792,
      "mape_percent": 33.592208457007786,
      "mean_signed_error": -7.013756750327312,
      "median_absolute_error": 36.401075066386284,
      "model_family": "RealMLP",
      "mse": 15788.279771452735,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension",
      "p90_absolute_error": 132.6837437649384,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5",
      "r_squared": 0.7128328771349854,
      "rmse": 125.65142168496438,
      "rmsle": 0.3896852047427889,
      "row_count": 99948,
      "sensitive_mode": "without_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 191.74051657000007,
      "top_five_percent_mae": 278.5455325828293,
      "wape_percent": 25.212853943798812
    }
  },
  "deep_prediction_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99"
    },
    "without_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5"
    }
  },
  "disagreement_summary": [
    {
      "comparison_id": "realmlp_without_vs_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 47.68279505342778,
      "highest_decile_residual_correlation": 0.9636875408818423,
      "mean_absolute_prediction_disagreement": 16.691883310505084,
      "median_absolute_prediction_disagreement": 9.292098685819383,
      "opposite_signed_error_percent": 9.070716772721815,
      "pearson_prediction_correlation": 0.9843433578350852,
      "pearson_residual_correlation": 0.9643741298382964,
      "second_candidate_lower_absolute_error_percent": 52.31720494657222,
      "spearman_prediction_correlation": 0.9887334489607951,
      "spearman_residual_correlation": 0.9437204953726724
    },
    {
      "comparison_id": "realmlp_with_vs_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 50.65634129747468,
      "highest_decile_residual_correlation": 0.9731624204509146,
      "mean_absolute_prediction_disagreement": 14.214082689582696,
      "median_absolute_prediction_disagreement": 8.302328345393661,
      "opposite_signed_error_percent": 7.9461319886340895,
      "pearson_prediction_correlation": 0.9891892219308128,
      "pearson_residual_correlation": 0.9746284352649397,
      "second_candidate_lower_absolute_error_percent": 49.33865610117261,
      "spearman_prediction_correlation": 0.9920515014896281,
      "spearman_residual_correlation": 0.958912522779644
    }
  ],
  "ensemble_status": "rejected",
  "ensemble_test_prediction_count": 0,
  "evaluation_label": "Post-Test Extension",
  "inherited_stage5a_governance_status": "PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION",
  "model_fit_calls": 0,
  "new_boosting_prediction_count": 0,
  "next_stage": "Stage 6",
  "official_comparison": [
    {
      "deep_minus_stage4l": 0.6481138711769034,
      "deep_value": 62.15974508887792,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mae",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518561,
      "stage4l_value": 61.511631217701016
    },
    {
      "deep_minus_stage4l": -34.456985572640406,
      "deep_value": 15788.279771452735,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.2177688101733812,
      "stage4l_value": 15822.736757025375
    },
    {
      "deep_minus_stage4l": -0.13703866424800992,
      "deep_value": 125.65142168496438,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.10894374878869242,
      "stage4l_value": 125.78846034921239
    },
    {
      "deep_minus_stage4l": 0.0006267252387677225,
      "deep_value": 0.7128328771349854,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "r_squared",
      "metric_direction": "higher_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.08799772890182062,
      "stage4l_value": 0.7122061518962177
    },
    {
      "deep_minus_stage4l": 0.005824346670568303,
      "deep_value": 0.3896852047427889,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmsle",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.5173067396917284,
      "stage4l_value": 0.3838608580722206
    },
    {
      "deep_minus_stage4l": 0.46011577283200467,
      "deep_value": 33.592208457007786,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.3887313947173658,
      "stage4l_value": 33.13209268417578
    },
    {
      "deep_minus_stage4l": 0.8113729991365801,
      "deep_value": 36.401075066386284,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "median_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 2.279797109858979,
      "stage4l_value": 35.5897020672497
    },
    {
      "deep_minus_stage4l": 0.2628839669398353,
      "deep_value": 25.212853943798812,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "wape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518475,
      "stage4l_value": 24.949969976858977
    },
    {
      "deep_minus_stage4l": 2.5404177238954535,
      "deep_value": -7.013756750327312,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mean_signed_error",
      "metric_direction": "closer_to_zero",
      "official_selection_effect": "none",
      "relative_difference_percent": -26.58960992129168,
      "stage4l_value": -9.554174474222766
    },
    {
      "deep_minus_stage4l": 1.1757907821593108,
      "deep_value": 132.6837437649384,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "p90_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.8940834036959574,
      "stage4l_value": 131.5079529827791
    },
    {
      "deep_minus_stage4l": -3.7575822697856154,
      "deep_value": 191.7405165

## 27. Independent Review and Repairs

This section checks independent review and repairs from saved, validated artifacts. It does not train, tune, or generate predictions.

In [28]:
path=ROOT/'artifacts/reports/stage5c_reviewer.md'
print(path.read_text(encoding='utf-8') if path.exists() else 'Independent review runs after Notebook execution; no finding is hidden.')

# Stage 5C Independent Review

Review scope: read-only independent review of `Stage 5C — Post-Test Deep and Ensemble Evaluation`. I independently inspected the frozen prerequisites, hashes, Test governance, loader implementation and sentinel, all prediction attempts, prediction files, metrics, paired Bootstrap, sensitive accuracy wording, disagreement and tail results, figures, Registry evidence, Notebook executions, protected recheck, State files, and Stage 6 handoff. I changed no model, prediction, result, Registry, Notebook, State file, or prior-Stage artifact.

Review outcome: blocked by one unresolved Major deliverable-consistency issue. There are zero Critical and one Minor issue.

## Evidence that passes

### Stage 4L official identity and reproduction

- `artifacts/reports/stage4l_verification.json` is PASS. The official pre-registered primary is `stage4l__blend__without_sensitive`, not a Candidate chosen from the observed Test leaderboard.
- The Stage 4L pre-Test freeze SHA-256 independently matches `6c4aece5c82077be1932060f935fb4ce70213ded591ccdd41b2d42179f92c3b7`. Its frozen blend weights are CatBoost 0.60, LightGBM 0.20, and XGBoost 0.20.
- The official prediction SHA-256 independently matches `9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed`.
- Independent calculation on its 99,948 saved rows reproduces MAE 61.511631217701, MSE 15822.736757025375, RMSE 125.788460349212, R-squared 0.712206151896, RMSLE 0.383860858072, MAPE 33.132092684176%, median absolute error 35.589702067250, WAPE 24.949969976859%, mean signed error -9.554174474223, P90 absolute error 131.507952982779, threshold-defined top-decile MAE 195.498098839786, top-five-percent MAE 287.063969348949, and negative prediction rate 0.000020010405. The separate qcut decile-10 summary correctly has MAE 195.913129618068; this is not the frozen threshold metric.
- Stage 4L remains the official pre-registered evaluation and is not replaced by Stage 5C.

### Stage 5A and Stage 5B prerequisites

- Stage 5A is accepted as `PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION`. The historical literal zero-Test-loading check remains visibly FAIL: 99,948 Test rows and source targets were transiently materialized in the historical incident, while zero Test rows entered learned preprocessing, category-vocabulary fitting, target transformation, model fitting, selection, or Validation metrics. The accepted incident is `accepted_procedural_test_row_materialization_without_demonstrated_statistical_leakage`; no refit was required.
- The without-sensitive bundle/model SHA-256 values independently match `0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006` and `be05e4f293cd719033c17862324e2c6f18673322b71ca79eb8c07dfa93f7efa3`.
- The with-sensitive bundle/model SHA-256 values independently match `d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600` and `e02ec0ab4f448a63dfd7a5a4e2f0785ce7542a0c8a947c2632cce13f78a9ed46`.
- Both clean Reload reports, effective configurations, reference predictions, and fixed-epoch proofs validate. They prove RealMLP, raw target, CPU, float32, epoch 30, early stopping disabled, best-checkpoint restoration disabled, 399,788 Train rows, and zero Test rows in fit.
- Stage 5B Verification and Reviewer are PASS. The frozen specification hash is `dba45a5966b3fa2f3b59a230ef1a801b17a9f5c0e1bbd5217418b5122799d0d5`; the Handoff hash is `12a7de3fa4a5ee43d91718b114827ef78a4c8d7aaffe199d0876597f2bf03fa6`.
- The attempted 0.50 Deep / 0.50 Stage 4 blend has Validation MAE 62.853024 but RMSE worsening 0.345731%, above the frozen 0.25% limit. The ensemble is therefore rejected and Test-ineligible. Frozen Deep evaluation is eligible.

### Freeze, Test membership, and safe access

- The Stage 5C protected baseline existed before Test-value access and protects 621 prior files plus the prior Registry prefix.
- The pre-evaluation freeze SHA-256 is `ea710f9369d9c9c4a37215ba030a999d154375881e1ecea5d4c0be010082cbaa`, timestamped `2026-07-15T23:49:48.051696+00:00`. First Stage 5C Test-artifact access was later, at `2026-07-15T23:49:59.132268+00:00`; first source Feature access was later still, at `2026-07-15T23:52:07.915625+00:00`.
- The freeze fixes two Deep Candidates, one official comparator, zero ensembles, 13 metrics, two paired comparisons, seed 42, 500 resamples, ten figures, seven Registry IDs, and the retry limits. I found no post-freeze Candidate, bundle, comparator, metric, Bootstrap, sensitive-policy, ensemble-eligibility, or Registry-ID change.
- Saved membership independently contains 399,788 unique Train IDs and 99,948 unique Test IDs with zero overlap. The Test-ID file hash is `b01edf609d3102351b848d166e4db885da56db66a1fe441496e470dcf57770cb`; sorted Test membership hashes to `e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e`.
- The canonical target comes only from the immutable official Stage 4L prediction. Its independent array hash is `889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a`.
- `stage5_safe_row_loader.py` uses callable `skiprows` and `usecols`, so excluded physical rows are skipped at the parser boundary before requested-field conversion. The synthetic sentinel passed with excluded invalid Feature and target values kept outside converters.
- The source hashes independently remain `e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c` without sensitive Features and `6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede` with sensitive Features.
- Exact Test Feature materialization is 99,948 rows per successful mode. Across all three physical attempts it is 299,844 Test Feature rows. Train Feature rows materialized, excluded rows converted, source target columns requested, and source target values materialized are all zero. The prohibited legacy loader is not called.

### Frozen inference and prediction artifacts

- There were exactly three physical attempts. `without_sensitive_attempt1` failed on a metadata field check after safe Feature loading and before prediction; it recorded zero prediction calls. `without_sensitive_attempt2_technical_retry1` passed with one prediction call. `with_sensitive_attempt1` passed with one prediction call.
- The repaired without-sensitive manifest now preserves both attempt IDs and correctly reports physical-attempt count 2. The aggregate attempts report correctly reports three physical attempts and two successful prediction artifacts.
- The two valid prediction files contain exactly 99,948 unique, sorted, identical Test IDs and exact canonical targets. All predictions are finite and on the original scale. Error formulas and all constant metadata columns are correct.
- Without-sensitive prediction SHA-256: `972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5`.
- With-sensitive prediction SHA-256: `b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99`.
- Static source inspection finds no model or preprocessing fit call. Attempt reports record zero model fits and zero preprocessing fits. There are exactly two successful full-Test prediction calls, one per mode.
- No Stage 5C ensemble Test prediction, rejected-ensemble prediction, weighted Test combination, or new Boosting prediction exists.

### Metrics, Bootstrap, accuracy-only comparison, and disagreement

- Independent calculation reproduces the complete metric rows. Without-sensitive RealMLP: MAE 62.159745088878, RMSE 125.651421684964, RMSLE 0.389685204743, R-squared 0.712832877135, threshold top-decile MAE 191.740516570000, and top-five-percent MAE 278.545532582829. With-sensitive RealMLP: MAE 61.821113730188, RMSE 125.020163634781, RMSLE 0.389632861747, R-squared 0.715711017303, threshold top-decile MAE 190.956325631039, and top-five-percent MAE 277.236066435256.
- The primary descriptive comparison is without-sensitive RealMLP minus Stage 4L: MAE +0.648113871177 (+1.053644%), RMSE -0.137038664248, RMSLE +0.005824346671, and R-squared +0.000626725239. Stage 4L remains official.
- Independent seed-42, 500-resample paired Bootstrap reproduces comparison 1: point +0.648113871177, mean +0.647066287958, median +0.643700944844, 95% interval [0.453880417082, 0.845481073377], first-Candidate win proportion 0.0.
- It also reproduces comparison 2, with-sensitive minus without-sensitive: point -0.338631358690, mean -0.336300459564, median -0.332807769302, 95% interval [-0.499985401070, -0.185014668044], first-Candidate win proportion 1.0. Both are descriptive Post-Test evidence and caused no selection.
- The current lightweight comparison artifacts correctly treat mean signed error as a closer-to-zero metric. They say absolute bias is smaller for without-sensitive RealMLP than Stage 4L and smaller for with-sensitive than without-sensitive.
- Sensitive wording is accuracy-only, not a fairness audit, equal-treatment or equal-opportunity result, or causal claim. It sends full fairness work to Stage 7.
- Independent disagreement calculation reproduces prediction correlation 0.984343, residual correlation 0.964374, mean/median disagreement 16.691883/9.292099, RealMLP lower-error rate 47.682795%, Stage 4L lower-error rate 52.317205%, opposite-sign rate 9.070717%, and highest-decile residual correlation 0.963688. Deep-mode prediction correlation is 0.989189 with mean/median difference 14.214083/8.302328.
- Target-decile, tail, and disagreement-by-decile tables use the same membership and reproduce from the saved predictions.

### Registry, figures, Notebook structure, protection, and handoff

- The main Registry has 362 unique IDs, exactly seven `stage5c__` IDs, and the exported seven rows equal the seven appended main rows. The exact 355-row prior byte prefix hashes to `da5501ee01e2131c642ca34af570ea7775cdce8a1cfa5a373a54c6cef66b4b5c`; second upsert action is REUSED. There is no ensemble Registry row.
- All ten required high-resolution PNG figures and ten plotting-data CSVs exist. Their current hashes match the visualization manifest. Candidate membership, row hash, Post-Test label, and interpretation scope are correct. The dense disagreement view saves 20,000 deterministic row IDs selected with seed 42.
- The Notebook has one standalone official title, Sections 0 through 29 exactly once, 30 code cells, execution counts and saved output for all 30, and no error output. Its source contains no fit, source loader, bundle loader, or prediction call.
- Execution attempt 1 failed before artifact work. Attempt 2 was the successful complete artifact-loading run. Attempt 3 was the successful cache-only run. Both successful execution reports record zero source access, model loading, fit, prediction generation, Bootstrap recalculation, and Registry duplication.
- The protected recheck reports PASS for 621/621 prior files, zero mismatch, unchanged source hashes, and preserved prior Registry prefix.
- The Stage 6 handoff exists, its current referenced hashes validate, it includes exactly the two Deep predictions and the official comparator, and it forbids Stage 6 model reruns. Stage 6 has not started.
- Final `stage5c_verification.json` is intentionally pending this Review, which is the required order. That pending file is not itself a pre-review defect.

## Major issue

1. **The executed Notebook is stale after an accepted scientific-reporting correction.** The current official-comparison and sensitive-accuracy CSV/JSON artifacts correctly classify `mean_signed_error` as `closer_to_zero`. However, the saved Notebook output in Section 17 still displays `lower_is_better` and incorrectly says the Stage 4L value -9.554 is favored over RealMLP -7.014. Section 19 likewise contains the old signed-bias direction for the two Deep modes. Therefore the required artifact-loading Notebook no longer displays the current validated artifacts. This is a deliverable-consistency failure, not a prediction, metric-value, model-selection, or governance failure.

The three-attempt Notebook budget is exhausted. Closing this issue requires explicit human approval for one fourth, clean, artifact-loading execution. Hand-editing saved outputs is not acceptable execution evidence.

## Minor issue

1. The required summary dashboard is numerically correct, but the rotated top-row model labels overlap the lower-row subplot titles. The ten individual analytical figures remain readable, so this is a presentation defect rather than a scientific blocker.

## Remaining risks

- Stage 5C is a descriptive Post-Test Extension. The same Test set had already been consumed in Stage 4L, so Stage 5C cannot establish a new unbiased winner. A new independent holdout is required for another unbiased final comparison.
- The models are highly correlated. Practical complementarity may be limited even where tail metrics differ.
- The sensitive comparison is accuracy-only; subgroup fairness remains unmeasured in this Stage.
- Future-data performance may differ from this saved Test evidence.

## Recommended fixes

1. Obtain human approval for exactly one fourth Notebook attempt.
2. Run the existing Notebook from a clean kernel in artifact-loading mode only. It must perform no source access, model or bundle loading, fit, prediction generation, Bootstrap recomputation, Registry write, or prediction regeneration.
3. Confirm 30/30 code cells execute with saved outputs and zero errors; specifically confirm Sections 17 and 19 display `closer_to_zero` and the current signed-bias interpretations.
4. Update only the Notebook execution evidence, Reviewer adjudication/follow-up, current State, protected recheck if required by the finalizer, and final Verification. Do not change any prediction or frozen decision.
5. Optionally improve dashboard spacing in a later presentation-only revision; do not use a visual repair to change any result.

## Done-Criteria disposition

All model/data/governance Done Criteria pass: prerequisites, historical Stage 5A disclosure, freeze-before-access timing, protected baseline, safe parser-boundary loading, exact membership and canonical target, source immutability, exactly two valid Deep predictions, zero fits, zero ensemble/new Boosting predictions, full metrics, both Bootstraps, accuracy-only sensitive comparison, decile/tail/disagreement results, Post-Test labels, Registry prefix/idempotence, ten figures, protected recheck, and Stage 6 handoff.

The complete/cache-only Notebook criterion is not currently satisfied against the repaired current artifact set because the saved output is stale. Consequently, Reviewer PASS, final Verification PASS, final no-blocker State, and the Stage 6 Next Step cannot be issued yet.

Critical issues: 0
Major issues: 1
Final recommendation: BLOCKED

## 28. Stage 5C Verification

This section checks stage 5c verification from saved, validated artifacts. It does not train, tune, or generate predictions.

In [29]:
path=ROOT/'artifacts/reports/stage5c_preliminary_verification.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "checks": {
    "all_required_artifacts_exist": true,
    "ensemble_test_prediction_absent": true,
    "model_fit_calls_zero": true,
    "new_boosting_prediction_count_zero": true,
    "preprocessing_fit_calls_zero": true,
    "source_target_values_zero": true,
    "train_feature_rows_zero": true,
    "two_prediction_artifacts": true
  },
  "created_at_utc": "2026-07-15T23:54:01.157924+00:00",
  "evaluation_label": "Post-Test Extension",
  "stage_id": "stage5c",
  "status": "PASS"
}

## 29. Stage 5C Completion Note

This section checks stage 5c completion note from saved, validated artifacts. It does not train, tune, or generate predictions. Stage 4L remains the official pre-registered Test evaluation. Stage 5C is descriptive only.

In [30]:
path=ROOT/'artifacts/results/stage5/posttest_evaluation/stage5c_evaluation_summary.json'
assert path.exists(), path
if path.suffix == '.json':
    data=json.loads(path.read_text(encoding='utf-8'))
    print(json.dumps(data, indent=2, ensure_ascii=False)[:12000])
elif path.suffix == '.csv':
    data=pd.read_csv(path)
    display(data.head(12))
    print({'rows':len(data),'columns':list(data.columns)})
else:
    print(path.read_text(encoding='utf-8')[:12000])

{
  "bootstrap_summaries": [
    {
      "bootstrap_mean": 0.6470662879579675,
      "bootstrap_median": 0.6437009448438786,
      "ci_2_5": 0.4538804170824676,
      "ci_97_5": 0.8454810733773875,
      "comparison_id": "realmlp_without_minus_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "first_candidate_win_proportion": 0.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": 0.6481138711769034,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage4l__blend__without_sensitive",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    },
    {
      "bootstrap_mean": -0.336300459564,
      "bootstrap_median": -0.33280776930222444,
      "ci_2_5": -0.4999854010698824,
      "ci_97_5": -0.18501466804360983,
      "comparison_id": "realmlp_with_minus_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "first_candidate_win_proportion": 1.0,
      "interpretation": "Negative values favor the first-named Candidate. This is descriptive and caused no selection.",
      "point_mae_difference": -0.3386313586895753,
      "resamples": 500,
      "row_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "second_candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "seed": 42,
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a"
    }
  ],
  "bundle_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__with_sensitive__fixed_epoch30__technical_retry1.joblib",
      "sha256": "d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7a9266aca3de299f600"
    },
    "without_sensitive": {
      "path": "artifacts/models/deep/core_final/stage5a2__realmlp__full_train__without_sensitive__direct_no_refit_recovery2.joblib",
      "sha256": "0d2dc108578512022608fee31676ced4d3d65d178f3d77b2418011057eff7006"
    }
  },
  "deep_candidate_metrics": {
    "stage5c__realmlp__with_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__with_sensitive__test_evaluation",
      "descriptive_mae_rank": 2,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 61.821113730188344,
      "mape_percent": 33.69601671665242,
      "mean_signed_error": -6.440909963862778,
      "median_absolute_error": 36.132470639483515,
      "model_family": "RealMLP",
      "mse": 15630.041315267528,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension_accuracy_only",
      "p90_absolute_error": 131.47486522058995,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "prediction_sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99",
      "r_squared": 0.7157110173026984,
      "rmse": 125.02016363478144,
      "rmsle": 0.38963286174723183,
      "row_count": 99948,
      "sensitive_mode": "with_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 190.95632563103865,
      "top_five_percent_mae": 277.2360664352556,
      "wape_percent": 25.075500372364072
    },
    "stage5c__realmlp__without_sensitive__test_evaluation": {
      "candidate_id": "stage5c__realmlp__without_sensitive__test_evaluation",
      "descriptive_mae_rank": 3,
      "evaluation_label": "Post-Test Extension",
      "evaluation_stage": "Stage 5C",
      "mae": 62.15974508887792,
      "mape_percent": 33.592208457007786,
      "mean_signed_error": -7.013756750327312,
      "median_absolute_error": 36.401075066386284,
      "model_family": "RealMLP",
      "mse": 15788.279771452735,
      "negative_prediction_rate": 0.0,
      "official_result_role": "post_test_extension",
      "p90_absolute_error": 132.6837437649384,
      "prediction_path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "prediction_sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5",
      "r_squared": 0.7128328771349854,
      "rmse": 125.65142168496438,
      "rmsle": 0.3896852047427889,
      "row_count": 99948,
      "sensitive_mode": "without_sensitive",
      "target_hash": "889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a",
      "test_row_id_hash": "e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e",
      "top_decile_mae": 191.74051657000007,
      "top_five_percent_mae": 278.5455325828293,
      "wape_percent": 25.212853943798812
    }
  },
  "deep_prediction_paths_and_hashes": {
    "with_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv",
      "sha256": "b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99"
    },
    "without_sensitive": {
      "path": "artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv",
      "sha256": "972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5"
    }
  },
  "disagreement_summary": [
    {
      "comparison_id": "realmlp_without_vs_stage4l_primary",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 47.68279505342778,
      "highest_decile_residual_correlation": 0.9636875408818423,
      "mean_absolute_prediction_disagreement": 16.691883310505084,
      "median_absolute_prediction_disagreement": 9.292098685819383,
      "opposite_signed_error_percent": 9.070716772721815,
      "pearson_prediction_correlation": 0.9843433578350852,
      "pearson_residual_correlation": 0.9643741298382964,
      "second_candidate_lower_absolute_error_percent": 52.31720494657222,
      "spearman_prediction_correlation": 0.9887334489607951,
      "spearman_residual_correlation": 0.9437204953726724
    },
    {
      "comparison_id": "realmlp_with_vs_without_sensitive",
      "evaluation_label": "Post-Test Extension",
      "first_candidate_lower_absolute_error_percent": 50.65634129747468,
      "highest_decile_residual_correlation": 0.9731624204509146,
      "mean_absolute_prediction_disagreement": 14.214082689582696,
      "median_absolute_prediction_disagreement": 8.302328345393661,
      "opposite_signed_error_percent": 7.9461319886340895,
      "pearson_prediction_correlation": 0.9891892219308128,
      "pearson_residual_correlation": 0.9746284352649397,
      "second_candidate_lower_absolute_error_percent": 49.33865610117261,
      "spearman_prediction_correlation": 0.9920515014896281,
      "spearman_residual_correlation": 0.958912522779644
    }
  ],
  "ensemble_status": "rejected",
  "ensemble_test_prediction_count": 0,
  "evaluation_label": "Post-Test Extension",
  "inherited_stage5a_governance_status": "PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION",
  "model_fit_calls": 0,
  "new_boosting_prediction_count": 0,
  "next_stage": "Stage 6",
  "official_comparison": [
    {
      "deep_minus_stage4l": 0.6481138711769034,
      "deep_value": 62.15974508887792,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mae",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518561,
      "stage4l_value": 61.511631217701016
    },
    {
      "deep_minus_stage4l": -34.456985572640406,
      "deep_value": 15788.279771452735,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.2177688101733812,
      "stage4l_value": 15822.736757025375
    },
    {
      "deep_minus_stage4l": -0.13703866424800992,
      "deep_value": 125.65142168496438,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmse",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": -0.10894374878869242,
      "stage4l_value": 125.78846034921239
    },
    {
      "deep_minus_stage4l": 0.0006267252387677225,
      "deep_value": 0.7128328771349854,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "r_squared",
      "metric_direction": "higher_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.08799772890182062,
      "stage4l_value": 0.7122061518962177
    },
    {
      "deep_minus_stage4l": 0.005824346670568303,
      "deep_value": 0.3896852047427889,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "rmsle",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.5173067396917284,
      "stage4l_value": 0.3838608580722206
    },
    {
      "deep_minus_stage4l": 0.46011577283200467,
      "deep_value": 33.592208457007786,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "mape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.3887313947173658,
      "stage4l_value": 33.13209268417578
    },
    {
      "deep_minus_stage4l": 0.8113729991365801,
      "deep_value": 36.401075066386284,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "median_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 2.279797109858979,
      "stage4l_value": 35.5897020672497
    },
    {
      "deep_minus_stage4l": 0.2628839669398353,
      "deep_value": 25.212853943798812,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "wape_percent",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 1.0536444219518475,
      "stage4l_value": 24.949969976858977
    },
    {
      "deep_minus_stage4l": 2.5404177238954535,
      "deep_value": -7.013756750327312,
      "descriptive_interpretation": "Observed value favors frozen RealMLP",
      "evaluation_label": "Post-Test Extension",
      "metric": "mean_signed_error",
      "metric_direction": "closer_to_zero",
      "official_selection_effect": "none",
      "relative_difference_percent": -26.58960992129168,
      "stage4l_value": -9.554174474222766
    },
    {
      "deep_minus_stage4l": 1.1757907821593108,
      "deep_value": 132.6837437649384,
      "descriptive_interpretation": "Observed value favors Stage 4L primary",
      "evaluation_label": "Post-Test Extension",
      "metric": "p90_absolute_error",
      "metric_direction": "lower_is_better",
      "official_selection_effect": "none",
      "relative_difference_percent": 0.8940834036959574,
      "stage4l_value": 131.5079529827791
    },
    {
      "deep_minus_stage4l": -3.7575822697856154,
      "deep_value": 191.7405165